KNOWN = {
    # ---- NCR 53C90 SCSI driver, rest of the bus-phase state machine (sc = mg+$186 softc) ----
    0x0100e05e: ("scsi_phase_datain", "DATA IN phase: set up DEV2M DMA chain, ESP count, cmd $90 DMA-xfer, ESP_DMA_CTRL=$38 (or pad if count 0)"),
    0x0100e0e6: ("scsi_phase_status", "STATUS phase: sc state=3, ESP cmd $11 (Initiator Command Complete)"),
    0x0100e0f4: ("scsi_phase_msgin", "MESSAGE IN phase: sc state=7, ESP cmd $10 (Transfer Information, PIO)"),
    0x0100e106: ("scsi_phase_msgout_err", "MESSAGE OUT phase is unexpected: abort with 'SCSI msgout phase'"),
    0x0100e10c: ("scsi_phase_error", "common tail of the phase handlers: scsi_abort(sc, msg)"),
    0x0100e11e: ("scsi_msgin_done", "after MSG IN byte: expect COMMAND COMPLETE (0) and FUNCCMPLT, state=5, ESP cmd $12 (Message Accepted)"),
    0x0100e188: ("scsi_abort", "print 'sc: %s', stop SCSI DMA (ESP_DMA_CTRL=$20), mark sd disconnected, reset ESP via sub_0100d9b4(0,0)"),
    # ---- SCSI disk ('sd') boot device ops table at $0101b1b4 ----
    0x0100e1ec: ("sd_open", "devops[0]: alloc sd (mg+$17e), reset ESP, find n-th target by INQUIRY, START UNIT, READ CAPACITY -> bd blksize/nblocks"),
    0x0100e2f0: ("sd_close", "devops[1]: no-op"),
    0x0100e2f8: ("sd_find_target", "scan targets 0..6 with INQUIRY; return the unit-th responding target or -1 (stops on bus hung)"),
    0x0100e356: ("sd_inquiry", "INQUIRY $12 len $42 into sd data buf; ok if device type 0,4,5,7,8; 3 tries"),
    0x0100e40a: ("sd_read_capacity", "READ CAPACITY $25 (8 bytes) into sd data buf; returns buf ptr (last LBA, blk len) or 0; 3 tries"),
    0x0100e49a: ("sd_request_sense", "REQUEST SENSE $03 len 14 into sd data buf; 3 tries; 1 s delay on BUSY"),
    0x0100e548: ("sd_start_unit_wait_ready", "START STOP UNIT $1b (Immed, Start) then TEST UNIT READY loop; prints 'waiting for drive to come ready' + dots"),
    0x0100e646: ("sd_read", "devops[2](mg,bd,blkno,addr,len): READ(6) $08 via DMA, len must be multiple of blksize, 3 tries; returns bytes or -1"),
    0x0100e726: ("sd_write_stub", "devops[3]: no-op (no write support in ROM)"),
    0x0100e72e: ("sd_label_blkno", "devops[4](mg,bd,size,i): block number of disk-label copy i = ceil(size/blksize)*i"),
    0x0100e750: ("sd_command", "issue sd CDB via sub_0100db8e; on CHECK CONDITION do REQUEST SENSE, on BUSY wait 1 s; returns 1 ok / 0 fail"),
    0x0100e7ee: ("sd_print_error", "print '%s: ' + selection timeout / sense key / busy / disconnected / driver refused message"),
    # ---- generic NeXT DMA channel helpers (softc header shared by sc and od) ----
    0x0100e8cc: ("dma_init", "CSR=DMA_RESET, clear flags, sc+$38=16-byte scratch, sc+$e4=8K-aligned bounce buffer at top-of-RAM-64K"),
    0x0100e94a: ("dma_setup_chain", "(sc,chain,addr,len,dir): build 2-entry chain in bounce buffer (+scratch tail), copy data for M2DEV"),
    0x0100ea5a: ("dma_cleanup", "(sc,resid): dma_stop, copy scratch tail back, copy bounce buffer to caller for DEV2M"),
    0x0100eacc: ("dma_start", "(sc,chain,dir): CSR=dir|RESET|BUFRESET, load next/limit(+start/stop), CSR=dir|SETENABLE(|SETSUPDATE)"),
    0x0100eb90: ("dma_stop", "save CSR status bits (sc+$24), CSR=DMA_RESET, save 'next' reg (sc+$28), clear flags"),
    # ---- disk boot-block loader (fs ops table at $0101b1cc: open/close/load) ----
    0x0100ebc4: ("boot_fs_open", "fsops[0]: alloc 8K-aligned label buffer (mg+$182) + 8K sector cache, call devops[0] open"),
    0x0100ec4e: ("boot_fs_load", "fsops[2]: skip name to flags, read+check label, pick bootfile, load boot block 0/1 and run it"),
    0x0100ed2e: ("boot_read_label", "try label copies 0..3: read $1c48 bytes at devops[4] blkno, validate with boot_check_label"),
    0x0100edc4: ("boot_check_label", "NeXT/dlV2 ($1c48 B) or dlV3 ($230 B): check version, label_blkno and 16-bit checksum"),
    0x0100ee54: ("boot_exec_blk0", "(mg,bd,byteoff): read 1 KB, parse a.out/Mach-O header, load image, build 'dev(c,u,p)file' and jump"),
    0x0100ef50: ("boot_fs_seek", "set current byte offset (labelbuf+$1c50)"),
    0x0100ef66: ("boot_fs_read", "(mg,bd,dst,len): read through 8 KB block cache via devops[2]; returns len or -1 ('short read' by caller)"),
    0x0100f044: ("boot_fs_close", "fsops[1]: call devops[1] close"),
    # ---- Canon OMD-1 magneto-optical disk ('od') driver, devops table at $0101b376 ----
    0x0100f060: ("od_ctrl_init", "(regs,ctrl,quiet,nowait): probe OSP at $02112000, alloc od softc mg+$18a, write init/format/mark/flags regs, DMA $02000050"),
    0x0100f166: ("od_volume_init", "alloc od volume struct mg+$18e, drive type 'Canon OMD-1', read label via sub_010100aa, bd blksize=1024"),
    0x0100f22e: ("od_label_blkno", "devops[4](.,.,.,i): label copy sector from table $0101b358 (0, $3c460, -1, -1)"),
    0x0100f244: ("od_open", "devops[0]: refuse on machine type 1/3, ctrl must be 0, unit <=1, od_ctrl_init + od_volume_init"),
    0x0100f2c0: ("od_close", "devops[1]: no-op"),
    0x0100f2c8: ("od_read", "devops[2](mg,bd,blkno,addr,len): sub_01010004(cmd 2 read, ..., flags $80000); returns len"),
    0x0100f2fe: ("od_write_stub", "devops[3]: no-op"),
    0x0100f306: ("od_strategy", "(iob,flag): len must be multiple of sector size else error $16; od_start_io"),
    0x0100f35a: ("od_start_io", "copy iob sector/addr/len into od softc ($4254/$210/$4260/$4264), clear retry counters, dispatch cmd 1"),
    0x0100f3e0: ("od_cmd_dispatch", "(od,vol,cmd,iob): od+$4281=cmd, clear bits 30/29, jump via table $01012a7c[cmd-1]"),
    0x0100f43a: ("od_cmd_start", "cmd 1: clip chunk to track/alt-group, compute physical track+sector, select head or spiral-on/RID/eject"),
    0x0100f66c: ("od_cmd_seek_low", "cmd 2: send DRV_SEK (track & $fff) with head-select pending, next cmd from table $0101b3b2"),
    0x0100f696: ("od_cmd_resume", "cmd 8: clear bit 23 and re-dispatch saved cmd od+$4285"),
    0x0100f6ac: ("od_cmd_fail_ret", "cmd 12: return -1"),
    0x0100f6b2: ("od_cmd_check_motor", "cmd 13: DRV_RDS; if DS_STOPPED send DRV_STM start motor (cmd $e) else finish (cmd 14)"),
    0x0100f6fa: ("od_cmd_finish", "cmd 14: clear bits 24/17, mark iob done (|=2)"),
    0x0100f716: ("od_cmd_after_eject", "cmd 7: clear vol bits 15/14, od bit 23; bit 12 -> error finish else next chunk"),
    0x0100f734: ("od_cmd_next_chunk", "cmd 5: sectors -= done; advance addr/sector and re-run cmd 1, or mark iob done"),
    0x0100f778: ("od_cmd_error_finish", "cmd 6: print 'failed', iob+$1c=error code, iob |= 6"),
    0x0100f796: ("od_cmd_xfer", "cmd 3/4/9/10/11: write track hi/lo, sector|$10, count to OSP regs, od_issue, od_complete"),
    0x0100f7dc: ("od_complete", "read/clear OSP int status + err stat, map to error code, read drive status, retry/restore/re-spin/eject logic"),
    0x0100fadc: ("od_issue", "start MO DMA (chain, dir by op), send pending drive cmd or CSR2, write formatter cmd to CSR1, poll DMA complete"),
    0x0100fc00: ("od_drive_cmd", "(od,vol,cmd16,flags): CSR2=drive sel|$80, wait CMD_COMPL, write CSR_H/CSR_L, wait; err $3a/$3b on timeout"),
    0x0100fcec: ("od_print_error", "(od,action): 'od%d%c: %s %s (%s) trk:0:sec' using op name and error table $0101b1d8"),
    0x0100fdc6: ("od_read_drive_status", "DRV_RDS/RES/RHS status words -> od+$4266/$4268/$426a, map error bits via tables, then DRV_RID"),
    0x0100ff6a: ("od_drive_query", "(od,vol,regs,cmd,flags): send drive cmd, 40 us, CSR1=$20 read-status, return 16-bit reply from CSR_H/L"),
}
