# Generated by merge_names.py from names/*.py -- do not edit; edit the fragments.
KNOWN = {
    0x01000042: ('reset_bmap_cacr_setup', 'non-Turbo only: cacr=$8000, BMAP+4=$C7000000, then BMAP DRAM sizing loc_01000992 (a5=cont)'),  # 01000000.py
    0x01000062: ('reset_bmap_finish', 'non-Turbo: BMAP+$C=$80000000, +$38=$E1000000, +0=slot id, SCR2|=$800; falls into NCC probe'),  # 01000000.py
    0x01000092: ('reset_probe_ncc', 'bus-error target on Turbo (no BMAP): vbr=table2, write NCC+0=0; d2=$2000 if NCC present'),  # 01000000.py
    0x010000b0: ('reset_machine_dispatch', 'isp=SCR1(|d2), re-read $02200000 when type==4, msp=type; branch per machine type'),  # 01000000.py
    0x0100017e: ('reset_cube030_setup', 'type 0: cacr=$19, SCR2|=$1800, AT&T enet init bytes from dat_01014af8 -> $02106010..14'),  # 01000000.py
    0x010001f2: ('reset_nonturbo040_setup', 'types 1,2: BMAP $30/$34=$40000000 if cpu speed field==0, enet init bytes -> $02106010'),  # 01000000.py
    0x01000200: ('reset_nonturbo040_bmap', 'part of reset_nonturbo040_setup (jump-table target)'),  # 01000000.py
    0x0100027a: ('reset_color_station_setup', 'type 3: BMAP+$C=$C0000000, $02118190=$0A, $02118180=0, SCR2|=$80'),  # 01000000.py
    0x010002a6: ('reset_turbo_setup', 'types 4-B: cinva, MMU transparent (loc_01000c68), then tmc_reset_config'),  # 01000000.py
    0x010002b4: ('tmc_reset_config', 'TURBO: cacr=$8000; TMC ctrl $02200010 from SCR1 speed bits; ADB mask/config=0; TMC H/V timing'),  # 01000000.py
    0x010003cc: ('reset_int_mask_crc', 'int mask $02007800=0; CRC-32 of ROM body then header (loc_0100418e); error code in a0'),  # 01000000.py
    0x010003f0: ('reset_crc_stage2', 'compare body CRC with header +$1A (err 1), then CRC bytes 0..21'),  # 01000000.py
    0x0100041e: ('reset_pick_stack', 'compare header CRC (err 2); choose VRAM stack (mono) or DRAM bank probe (colour types 3,5,7,9,B)'),  # 01000000.py
    0x010004c2: ('reset_probe_vram_stack', 'mono: a7=VRAM base, probe 256 KB via loc_01003ca4 (err 3), cont sub_010004d0'),  # 01000000.py
    0x010004d0: ('reset_mg_in_vram', 'mono: mg at VRAM+$3F800, vbr=mg+$400, mg_sid, mg_machine_type, set mg ptr'),  # 01000000.py
    0x01000508: ('reset_probe_dram_stack', 'colour: loc_01003dfc finds first working 32 MB bank (err 5), cont sub_01000514 with a0=bank'),  # 01000000.py
    0x01000514: ('reset_mg_in_dram', 'colour/TURBO COLOR: mg at bank+$800, vbr=mg+$400, mg_sid/type, set mg ptr, sub_01003a9c(0)'),  # 01000000.py
    0x01000556: ('reset_install_vectors', 'd2=sub_01005cd2() (nvram TEST_DRAM), all 256 vectors=exc_common_entry, sub_0100ac8a, test panel, push $700 frame'),  # 01000000.py
    0x010005ae: ('exc_common_entry', 'every vector: save d0-d7/a0-a7,usp,sfc,dfc,vbr,cacr in $84-byte frame, sr=$2700, cacr=$8000, call exc_dispatch, rte'),  # 01000000.py
    0x01000654: ('mon_reenter_704', 'called on the new monitor stack: MMU transparent then sub_01000660'),  # 01000000.py
    0x01000660: ('mon_reenter_704_frame', 'vbr=arg, push fake frame vector $704 (PC=$04000000) and enter exc_common_entry'),  # 01000000.py
    0x0100067a: ('mg_set_ptr', 'store arg (mg pointer) at vbr+4 (unused vector slot 1)'),  # 01000000.py
    0x01000686: ('mg_get_ptr', 'return mg pointer from vbr+4'),  # 01000000.py
    0x01000690: ('cpu_get_vbr', 'd0 = vbr'),  # 01000000.py
    0x01000696: ('cpu_set_vbr', 'vbr = arg'),  # 01000000.py
    0x010006a0: ('cpu_get_ipl', 'd0 = (sr>>8)&7'),  # 01000000.py
    0x010006ac: ('mon_call_on_stack', 'switch a7 to arg0, copy 15 longs of args, jsr arg1 (used for kernel entry and $704 re-entry)'),  # 01000000.py
    0x010006f4: ('mon_return_trap', 'return address given to booted program: pushes fake vector $600 frame, enters exc_common_entry'),  # 01000000.py
    0x010006fa: ('mon_return_trap_frame', 'second half of mon_return_trap'),  # 01000000.py
    0x0100070e: ('cpu_moves_read_long', 'moves.l (addr) with sfc=arg2'),  # 01000000.py
    0x01000728: ('cpu_fc_read_word', 'read word from addr with sfc=arg2 (plain move.w, not moves)'),  # 01000000.py
    0x01000742: ('cpu_moves_read_byte', 'moves.b (addr) with sfc=arg2'),  # 01000000.py
    0x0100075e: ('cpu_moves_write_long', 'moves.l val,(addr) with dfc=arg2'),  # 01000000.py
    0x0100077c: ('cpu_moves_write_word', 'moves.w val,(addr) with dfc=arg2'),  # 01000000.py
    0x0100079a: ('cpu_moves_write_byte', 'moves.b val,(addr) with dfc=arg2'),  # 01000000.py
    0x010007c6: ('bf_insert', 'bfins d0,(a0){1:2} helper (args: value, addr, ...)'),  # 01000000.py
    0x010007e2: ('bf_extract', 'bfextu (a0){0:1} helper'),  # 01000000.py
    0x010007f4: ('mem_bmap_addr_scan', 'pre-stack helper: find address bits where BMAP probe (a6/a7) matches d2 pattern; result d0/d1, jmp (a4)'),  # 01000000.py
    0x010008e2: ('mon_enter_from_os', 'mg+$3AA callback: save sp,tc,cacr,itt/dtt at vbr+$100.., MMU transparent, then sub_01000930'),  # 01000000.py
    0x01000930: ('mon_enter_from_os_2', 'cacr=$8000, re-run BMAP DRAM sizing (non-Turbo) with cont sub_01000946'),  # 01000000.py
    0x01000946: ('mon_enter_from_os_restore', 'restore tc/itt/dtt/cacr/sp saved at vbr+$100.., pop BMAP+4, rts to OS caller'),  # 01000000.py
    0x01000992: ('mem_bmap_size_dram', 'NON-TURBO: BMAP register programming and DRAM bank sizing using move16 probes (a5=cont)'),  # 01000000.py
    0x010009de: ('mem_bmap_size_dram_2', 'stage 2 of mem_bmap_size_dram'),  # 01000000.py
    0x01000a1a: ('mem_bmap_size_dram_3', 'stage 3: choose BMAP+$1C mode, scan banks writing BMAP+$18'),  # 01000000.py
    0x01000a6e: ('mem_bmap_size_dram_4', 'stage 4: bank walk with BMAP+$18/$20/$14 probes, finish with jmp (a5)'),  # 01000000.py
    0x01000bae: ('mem_bmap_size_dram_5', 'stage 5 (alternate sizing path, BMAP+$1C=$90000000)'),  # 01000000.py
    0x01000c04: ('mem_bmap_size_dram_6', 'stage 6: BMAP+$18 final, BMAP+$1C=$B0000000, jmp (a5)'),  # 01000000.py
    0x01000c68: ('mmu_transparent_setup', 'tc=0, itt1/dtt1=$00FFC000 (all, cacheable), itt0/dtt0=$0200C040 (device, serialized), tc=$C000, jmp (a0)'),  # 01000000.py
    0x01000c9c: ('mg_init_machine', "zero km/addr, fmt='l', radix 16, sid, dmachip=$139 for types 0-2, BMAP/NCC ptrs per type, nvram read or default"),  # 01000000.py
    0x01000d64: ('mg_init_type1', 'type 1 (station mono): is_station=1, simm_type=0'),  # 01000000.py
    0x01000d6c: ('mg_init_type0_2', 'types 0,2 (cubes): is_station=0, simm_type=0, sockets=0'),  # 01000000.py
    0x01000d7a: ('mg_init_type3', 'type 3 (colour station): is_station=1, simm_type=1, sockets=2'),  # 01000000.py
    0x01000d86: ('mg_init_type6_7', 'types 6,7: NCC $02210000 + tag RAM $03E00000 pointers, then as types 4,5'),  # 01000000.py
    0x01000d96: ('mg_init_type4_5', 'TURBO STATION (4,5): is_station=1, simm_type=1, sockets=2, mg_sid=0'),  # 01000000.py
    0x01000dac: ('mg_init_typeA_B', 'types A,B: NCC pointers then as types 8,9'),  # 01000000.py
    0x01000dbc: ('mg_init_type8_9', 'types 8,9 (Turbo cube): is_station=0, simm_type=1, sockets=2'),  # 01000000.py
    0x01000e2e: ('mon_show_test_panel', "if nvram POT&$11: mg_init_machine, draw panel + 'Testing system ...'; returns $80 (mg_flags) else 0"),  # 01000000.py
    0x01000ec6: ('mon_init', 'C init: int reg ptrs, callbacks, DRAM sizing/tests, NCC, banner, nvram SIMM check, relocate mg, ADB init, POST'),  # 01000000.py
    0x0100187c: ('fd_pick_default_boot', "if bootcmd=='FD': select 82077, DOR=0 then $14; status bit2 (no drive) -> 'en' else 'fd'"),  # 01000000.py
    0x010018d4: ('exc_dispatch', 'C exception/monitor dispatcher: $700 first init, $704 device init+boot, $7C NMI/parity, $B4 trap13, else print'),  # 01000000.py
    0x01001d50: ('exc_nofault_skip6word', 'nofault resume: sp += 4 for 6-word frames (format 2,3)'),  # 01000000.py
    0x01001d56: ('exc_nofault_skip_fmt7', 'nofault resume: sp += $34 for format 7 (bus error) frames'),  # 01000000.py
    0x01001d5e: ('exc_nofault_bogus', "prints 'bogus stack frame' for frame formats 4-6"),  # 01000000.py
    0x01001d72: ('exc_nofault_resume', 'PC = mg_nofault, clear it, return (rte resumes in handler)'),  # 01000000.py
    0x01001dd8: ('mon_command_loop', "'NeXT> ' prompt: read line, password gate (nvram byte2 bits 2-5 == 6), dispatch via table dat_01011c40"),  # 01000000.py
    0x01001ef8: ('mon_cmd_password', "'P': read/retype 16-char password, store 6 bytes xor $4E at nvram+4, set mode 6, write nvram"),  # 01000000.py
    0x01001fd8: ('mon_cmd_boot', "'b': boot_arg=rest of line, boot_how=2, re-enter via mon_reenter_704 on monitor stack"),  # 01000000.py
    0x01001ffe: ('mon_cmd_aregs', "'a': address-register display/modify (continues at loc_0100218a)"),  # 01000000.py
    0x01002012: ('mon_cmd_d', "'d [n]': edit saved d0-d7 in the exception frame via param table sub_010145c8, prefix 'd'"),  # 01002000.py
    0x01002026: ('mon_cmd_r', "'r [reg]': edit saved processor regs (pc, sr, usp...) via table sub_01014730"),  # 01002000.py
    0x0100203a: ('mon_cmd_m', "'m': print memory configuration from mg_simm[4] + mg_region[4]; 4-socket or SIMM-pair wording by mg+$3ba"),  # 01002000.py
    0x0100213a: ('mon_cmd_p', "'p': edit NVRAM parameters (table sub_010148c0, base mg_nvram); writes NVRAM back if changed"),  # 01002000.py
    0x01002168: ('mon_cmd_s', "'s [sysreg]': edit intrstat/intrmask/scr1/scr2; table 010147f8 if non-Turbo else 0101485c"),  # 01002000.py
    0x0100218a: ('mon_cmd_regs_common', 'shared tail of a/d/r commands: mon_param_edit_table(args, table, frame, prefix)'),  # 01002000.py
    0x0100219a: ('mon_cmd_e', "'e': ec=print NVRAM error codes 15/16, ef/ej/eo=eject, else examine memory with fcode d3"),  # 01002000.py
    0x0100223a: ('mon_cmd_fcode', "'S [fcode]': set monitor function code d3 (0..7), prints 'Function code %d (%s)'"),  # 01002000.py
    0x01002278: ('mon_cmd_radix', "'R [radix]': set mg+$192 default input radix (byte), prints it"),  # 01002000.py
    0x010022b0: ('mon_cmd_help', "'?'/'h': print the monitor help text"),  # 01002000.py
    0x010022ba: ('mon_cmd_huh', "unknown command: prints 'Huh?'"),  # 01002000.py
    0x010022cc: ('mon_cmd_continue', "'c': restore d2-d6/a2-a5, unlk, rts = continue at last pc"),  # 01002000.py
    0x010022d6: ('mem_build_regions', 'fill mg_region[4] {base,size} at mg+$c8 from mg_simm codes; stride 16/8/32 MB, size table by class'),  # 01002000.py
    0x0100237a: ('mon_probe_read_byte', '*dst=*src byte with bus-error catch via mg+$1a4; returns 1 ok, 0 on bus error'),  # 01002000.py
    0x010023aa: ('mon_probe_read_byte_fail', 'bus-error continuation of mon_probe_read_byte: clear mg+$1a4, return 0'),  # 01002000.py
    0x010023b8: ('mon_probe_write_byte', '*dst=val byte with bus-error catch via mg+$1a4; returns 1 ok, 0 on bus error'),  # 01002000.py
    0x010023f6: ('mon_probe_read_long', '(mg, addr): read long with bus-error catch; 1 ok, 0 on bus error or mg==0'),  # 01002000.py
    0x01002426: ('mon_print_warning', 'set mg+$170 bit3/clear bit0 (once) then printf(str)'),  # 01002000.py
    0x01002462: ('mon_system_test_failed', "draw icons + 'System test failed' text; if arg!=0 loop forever in power-key handler"),  # 01002000.py
    0x010024f6: ('mon_password_check', "(force): ask 'Password: ' if NVRAM pw field==6 and not authenticated; 1=allowed, 0='Sorry'"),  # 01002000.py
    0x010025c0: ('mon_usage_error', 'print usage error message'),  # 01002000.py
    0x010025d4: ('mon_led_blink', '(n): blink SCR2 LED (bit0 of $0200D000) n times, 1M-iteration delay per phase'),  # 01002000.py
    0x01002630: ('mon_param_edit_table', '(line, table, base, prefix): interactive show/modify loop over 20-byte param entries; ret 1 if changed'),  # 01002000.py
    0x0100274e: ('mon_param_sysreg', 'param handler: %b print / hex store of a system register; SCR1 redirected to TMC $02200000 on Turbo'),  # 01002000.py
    0x010027e2: ('mon_param_bootcmd', "param handler for boot command string at nvram+$12, max 12 chars, '.' clears"),  # 01002000.py
    0x0100287c: ('mon_param_pot_bit', 'param handler: yes/no bit in NVRAM byte 14 (POT byte), mask = entry+4'),  # 01002000.py
    0x0100291a: ('mon_param_parity', 'param handler: yes/no bit2 of NVRAM byte 17 (USE_PARITY_MEM)'),  # 01002000.py
    0x010029aa: ('mon_param_reset_bit', 'param handler: yes/no bit in NVRAM long 0 (ni_reset); eject bit needs disk in drive 0'),  # 01002000.py
    0x01002a68: ('mon_examine_memory', "'e [lwb] [alist] [fmt]': cyclic examine/modify up to 8 addrs via moves with fcode; list at mg+$1aa"),  # 01002000.py
    0x01002c38: ('mon_print_help', "printf('%s', help text at $01014cd8)"),  # 01002000.py
    0x01002c54: ('mem_print_bad_sockets_nt', "(addr, pattern, &val, type): 'DRAM error type %d' + socket list bank*4+3-lane (non-Turbo)"),  # 01002000.py
    0x01002cd2: ('mem_report_error_nt', "(addr): print memory error, retest 55/AA, name bad sockets or 'Coupling dependent memory fault'"),  # 01002000.py
    0x01002d92: ('mem_bank_present_nt', '(base): clear 8 longs, read each twice; 1 if all read 0 (RAM present)'),  # 01002000.py
    0x01002dbe: ('mem_bank_size_nt', '(base): alias test at +4MB/+1MB; returns SIMM code 5=16MB,6=4MB,7=1MB page mode, 0=bad'),  # 01002000.py
    0x01002e24: ('mem_write_read_long', '(addr): write 12345678/EDCBA987, cpusha, 1 if first long reads back'),  # 01002000.py
    0x01002e4c: ('mem_config_test_nt', 'non-Turbo DRAM sizing: SCR2 bits 16+i/20+i per bank, fills mg_simm, BMAP parity probe; 0/1/2'),  # 01002000.py
    0x0100313c: ('mem_pattern_test_nt', '(base,size): 3 passes of DB6DB6DB,0,0 triple fill+verify, then 4 byte lanes; ret bad addr or 0'),  # 01002000.py
    0x01003224: ('mem_test_all_nt', 'non-Turbo full DRAM test: LED on, caches off, mem_pattern_test_nt per bank, report errors'),  # 01002000.py
    0x010032e0: ('mem_print_bad_socket_t', "(addr,type): 'DRAM error type %d', 'Check socket %d' = bank*2 + (addr&4?1:0)"),  # 01002000.py
    0x0100336a: ('mem_report_error_t', "(addr): print memory error, retest 55/AA, socket or 'One or both SIMMs in memory bank %d are bad'"),  # 01002000.py
    0x01003456: ('mem_pattern_test_t', '(base,size): same as mem_pattern_test_nt but 8 byte lanes (SIMM pair); ret bad addr or 0'),  # 01002000.py
    0x0100353e: ('mem_bank_absent_t', '(base): write 55555555,AAAAAAAA x3 to 16 bytes; returns 1 if readback differs (bank empty)'),  # 01002000.py
    0x01003598: ('mem_bank_size_t', '(addr): alias test at +8MB/+2MB; code 1=32MB pair,2=8MB,3=2MB (type3: 2=8MB_C), 0=bad'),  # 01002000.py
    0x0100361a: ('mem_config_test_t', 'Turbo DRAM sizing per bank (32MB stride, +0/+4 pair), parity probe, TMC ctrl bits 10/3; ret 0/1/2'),  # 01002000.py
    0x010039bc: ('mem_test_all_t', 'Turbo full DRAM test: caches off, mem_pattern_test_t per bank (skips stack page), report errors'),  # 01002000.py
    0x01003a9c: ('vid_vram_test', '(quiet): test 2MB VRAM ($0C000000 Turbo/$2C000000 type3) mask FFF0FFF0; blinks LED, prints failure'),  # 01002000.py
    0x01003c84: ('vid_vram_probe_fill', 'pre-stack helper: fill [a2,a3) with d1, verify, d0=bad addr or 0, jmp (a4)'),  # 01002000.py
    0x01003ca4: ('vid_vram_probe', 'reset: LED on, cacr=$8000, test 256KB at a0 with AA/55/incrementing; fail -> LED code 3 halt'),  # 01002000.py
    0x01003ce2: ('vid_vram_probe_pass2', 'continuation: 55555555 pass'),  # 01002000.py
    0x01003cfc: ('vid_vram_probe_pass3', 'continuation: incrementing-long pass, then restore cacr, LED off, jmp (a6)'),  # 01002000.py
    0x01003d4a: ('mem_burst_test_nt', '(base): 4-long pattern, caches on ($80008000), line-fill readback; 1 ok; leaves cacr=$8000'),  # 01002000.py
    0x01003dbe: ('mem_berr_parity_nt', 'temp bus-error vector for non-Turbo parity probe: BMAP+8=0, rte'),  # 01002000.py
    0x01003dcc: ('mem_dram_probe_fill', 'pre-stack helper: fill [a2,a3) with d1 (dbra), verify, jmp (a4)'),  # 01002000.py
    0x01003dfc: ('mem_dram_probe', 'reset (colour types): find first bank whose first 8KB passes 55/AA, DB6DB6DB, ~, incr; a0=bank, jmp (a7)'),  # 01002000.py
    0x01003e5c: ('mem_dram_probe_pass2', 'continuation: inverted pattern pass'),  # 01002000.py
    0x01003e76: ('mem_dram_probe_pass3', 'continuation: incrementing pass; success -> jmp (a7)'),  # 01002000.py
    0x01003e9e: ('mem_dram_probe_next', 'advance a0 by stride d3 until a6; none works -> LED code 5 halt'),  # 01002000.py
    0x01003eb2: ('mem_parity_probe_nt', '(base): BMAP+8=$80000000 (parity on), write patterns, result = BMAP+8 bit31 still set'),  # 01002000.py
    0x01003ece: ('mem_parity_probe_nt_done', 'tail: d0 = BMAP+8 & $80000000, BMAP+8 = 0, restore a2, rts'),  # 01002000.py
    0x01003ee8: ('mem_parity_probe_t', '(base): TMC ctrl |= $400 (parity on), write patterns; unlabeled entry called from $01003806'),  # 01002000.py
    0x01003f04: ('mem_parity_probe_t_done', 'tail: d0 = TMC ctrl & $400 (0 if NMI handler cleared it), then clear bit 10, rts'),  # 01002000.py
    0x01003f1e: ('mem_parity_probe_body', 'write 16B of 0, 16B of 01010101, 32 bytes with odd-parity byte pattern, read back, jmp (a2)'),  # 01002000.py
    0x01003f94: ('mem_berr_parity_vec_nt', 'vector 2 of temp table mem_vectors_nt: BMAP+8=0, rte'),  # 01002000.py
    0x01003fa2: ('mem_nmi_parity_vec_t', 'vector 31 (level-7 NMI) of mem_vectors_t: TMC $02200004=0, TMC ctrl &= ~$400, rte'),  # 01002000.py
    0x01003fc2: ('mem_vectors_nt', 'DATA: 12-entry vector table (all $010005ae, entry 2 = mem_berr_parity_vec_nt) used as VBR by type 3'),  # 01002000.py
    0x01003ff2: ('mem_vectors_t', 'DATA: 32-entry vector table (all $010005ae, entry 31 = mem_nmi_parity_vec_t) used as VBR on Turbo'),  # 01002000.py
    0x01004072: ('tmc_parity_init_range', 'rewrite longs a0..a1 with TMC ctrl bit10 set per word; leaves bit10 set. Turbo only. args: start,end'),  # 01004000.py
    0x010040a8: ('cache_push_data', 'cpusha dc: push dirty data cache lines'),  # 01004000.py
    0x010040ac: ('cache_inval_set_cacr', 'cinva both caches, set CACR from arg; returns old CACR in d0'),  # 01004000.py
    0x010040bc: ('cache_get_cacr_push', 'd0 = CACR, then cpusha dc'),  # 01004000.py
    0x010040c4: ('led_on', 'SCR2 |= 1 (SCR2_LED) via displacement arg (normally 0)'),  # 01004000.py
    0x010040d6: ('led_off', 'SCR2 &= ~1 (SCR2_LED) via displacement arg (normally 0)'),  # 01004000.py
    0x010040e8: ('led_blink_halt', 'C entry: blink LED $4(a7) times, long pause, repeat forever (never returns)'),  # 01004000.py
    0x010040ec: ('led_blink_loop', 'asm entry, a0 = blink count: SCR2 LED on/off n times, pause, loop forever'),  # 01004000.py
    0x01004142: ('snd_out_clear_underrun', 'KMS_Ctrl_Snd |= $20 (SNDOUT_DMA_UNDERRUN) with ints off; Turbo version'),  # 01004000.py
    0x01004156: ('snd_out_clear_underrun_wait', 'wait KMS TX bit6 while SNDOUT enabled, then KMS_Ctrl_Snd |= $20; non-Turbo'),  # 01004000.py
    0x0100418e: ('crc32_calc_asm', 'CRC-32 poly $04C11DB7 of d3 bytes at a1, LED on during calc, result d0, jmp (a0)'),  # 01004000.py
    0x010041e2: ('crc32_calc', 'C wrapper: crc32(buf $8(a6), len $c(a6)); continuation at $010041fe, d0 = CRC'),  # 01004000.py
    0x010041fe: ('crc32_calc_ret', 'continuation of crc32_calc: restore regs, unlk, rts'),  # 01004000.py
    0x01004208: ('vid_span_2bpp', 'expand run of 2bpp pixels (byte val, count) into 2bpp framebuffer via mg+$33c lut'),  # 01004000.py
    0x01004274: ('vid_span_8bpp', 'expand run of 2bpp pixels into 8bpp framebuffer (byte per pixel) via mg+$33c lut'),  # 01004000.py
    0x010042f4: ('vid_span_16bpp', 'expand run of 2bpp pixels into 16bpp framebuffer (word per pixel) via mg+$33c lut'),  # 01004000.py
    0x01004378: ('vid_span_32bpp', 'expand run of 2bpp pixels into 32bpp framebuffer (long per pixel) via mg+$33c lut'),  # 01004000.py
    0x010043fc: ('vid_draw_image_onscreen', 'ints off, mg+$368 := mg+$374 (visible fb), vid_draw_image(x,y,img), restore'),  # 01004000.py
    0x01004440: ('vid_draw_image', "draw NeXT image struct (type 'B' RLE,'U' raw,'S' table-RLE) at x,y; picks span fn by depth"),  # 01004000.py
    0x01004512: ('vid_draw_rle_image', "type 'B': (value,count) byte pairs per row, calls span fn"),  # 01004000.py
    0x0100457a: ('vid_draw_raw_image', "type 'U': packed 2bpp rows expanded per depth; raw copy if mg+$348 == -1"),  # 01004000.py
    0x0100471c: ('vid_draw_tbl_rle_image', "type 'S': n (value,count) table then index bytes per row"),  # 01004000.py
    0x010047ac: ('post_delay_9us', 'delay(9) wrapper used between register accesses in tests'),  # 01004000.py
    0x010047be: ('snd_out_clear_underrun_any', 'non-Turbo (mg+$194==$139): snd_out_clear_underrun_wait else snd_out_clear_underrun'),  # 01004000.py
    0x010047e6: ('post_scsi_dma_isr', 'ISR frame: save regs, post_scsi_dma_intr, rte (unused in POST: SCSI DMA int)'),  # 01004000.py
    0x0100480a: ('post_timer_isr', 'level-6 autovector ISR frame used by post_timer_test: calls post_timer_ack'),  # 01004000.py
    0x0100481a: ('post_snd_out_isr', 'level-6 autovector ISR frame used by sound test: calls post_snd_out_dma_stop'),  # 01004000.py
    0x0100483e: ('post_fpu_test', 'run fpu_test_regs(1), fpu_test_formats(2), fpu_test_arith(3); d0 = failing sub-test or 0'),  # 01004000.py
    0x01004872: ('post_snd_in_dma_reset', 'ISR body: sound-in DMA CSR $020000c0 = RESET|INITBUF(non-Turbo)/BUFRESET(Turbo)'),  # 01004000.py
    0x010048a6: ('post_scc_test', 'Z8530 loopback via $02118000: WR9 reset, 20-byte init table, tx/rx $40 both channels; d0 1-7'),  # 01004000.py
    0x01004a16: ('post_scsi_dma_intr', 'printf "SCSI DMA intr?\\n"'),  # 01004000.py
    0x01004a2a: ('post_scsi_test', 'ESP reset via ESP_DMA_CTRL $02114020, chip reset, FIFO 0..4 write/read check; d0 1-3'),  # 01004000.py
    0x01004ada: ('post_ext_scsi_test', 'ESP FIFO flush, transfer count $5555/$AAAA, config reg 0..255, illegal cmd INTR_ILL; d0 4-8'),  # 01004000.py
    0x01004bf0: ('post_enet_test', 'AT&T7213 loopback: drain rx, send/recv 1500B self-addr, filter test, broadcast; d0 1-7'),  # 01004000.py
    0x01004f12: ('post_ecc_test', 'MO drive (OSP $02112000) ECC encode/corrupt/correct via disk DMA $02000050; cubes only; d0 1-6'),  # 01004000.py
    0x010052d0: ('post_rtc_test', 'wait up to 1.1 s for RTC seconds reg ($20 old chip / $23 new) to change; d0 1 on timeout'),  # 01004000.py
    0x01005338: ('post_timer_ack', 'timer ISR body: read hardclock CSR $02116004, write 0 (disable)'),  # 01004000.py
    0x0100534e: ('post_timer_test', 'hardclock counter write/latch/readback 0..$FFFF then 1000us periodic int must fire; d0 2,3'),  # 01004000.py
    0x01005440: ('post_evcnt_test', 'event counter $0211A000 must tick, delay(1000) in 899..1100us, 100 deltas within 3; d0 1-3'),  # 01004000.py
    0x0100553a: ('post_evcnt_measured', 'event counter test: measured delay(1000) in d0 (us)'),  # 01004000.py
    0x010055f2: ('post_snd_out_overrun_intr', 'printf "Sound Out Over Run Interrupt.\\n"'),  # 01004000.py
    0x01005606: ('kms_send_cmd', 'wait KMS TX bit4 clear, KMS_Ctrl_Cmd $0200E003 = cmd, KMS_Data $0200E004 = data, delay 200us'),  # 01004000.py
    0x01005634: ('post_snd_out_dma_stop', 'ISR body: sound-out DMA CSR $02000040 = RESET(+INITBUF/BUFRESET), KMS cmd 7 (snd out off)'),  # 01004000.py
    0x0100567e: ('kms_set_volume', 'bit-bang volume chip via KMS CTRLOUT ($C4): 11 bits, chan sel $40/$80, 6-bit volume'),  # 01004000.py
    0x01005758: ('post_snd_out_test', 'play 8KB buffer (arg 1 silence / 0 sine) via sound-out DMA $02004040; d0 1 DMA err, 2 not done'),  # 01004000.py
    0x01005a46: ('post_run_all', 'POST master: FPU,SCC,SCSI,Enet,ECC(cubes),RTC,Timer,EvCnt,[SoundOut],[ExtSCSI]; d0 error code'),  # 01004000.py
    0x01005aa2: ('post_ret_fpu', 'POST master: FPU test returned (d0); error code $40|n'),  # 01004000.py
    0x01005ad2: ('post_ret_scc', 'POST master: SCC test returned (d0); error code $50|n'),  # 01004000.py
    0x01005b26: ('post_ret_enet', 'POST master: Enet test returned (d0); error code $70|n'),  # 01004000.py
    0x01005b5e: ('post_ret_ecc', 'POST master: ECC test returned (d0); error code $80|n'),  # 01004000.py
    0x01005b8e: ('post_ret_rtc', 'POST master: RTC test returned (d0); error code $90|n'),  # 01004000.py
    0x01005bbe: ('post_ret_timer', 'POST master: Timer test returned (d0); error code $C0|n; then EvCnt $D0|n, SoundOut $E0|n'),  # 01004000.py
    0x01005c64: ('post_ret_ext_scsi', 'POST master: Ext SCSI (and SCSI) returned (d0); error code $60|n; loop-mode key wait'),  # 01004000.py
    0x01005cd2: ('nvram_check_or_rtc_ramtest', 'read NVRAM: ok -> d0 = POT byte & $10 (TEST_DRAM); bad -> walking-1 RTC RAM test, LED 4 blinks, d0=1'),  # 01004000.py
    0x01005d44: ('fpu_test_regs', 'fmovem 8 patterns x 256 rotations through fp0-fp7, compare; d0 != 0 on error'),  # 01004000.py
    0x01005d82: ('fpu_test_regs_pattern', 'inner: push 8 x (d1,d2,d3), fmovem in/out, compare 256 shifted variants'),  # 01004000.py
    0x01005dd2: ('fpu_test_formats', 'fmove.l/.s/.d/.x round trips of 1024 ints from $8000; d0 != 0 on error'),  # 01004000.py
    0x01005e1c: ('fpu_test_arith', 'fadd/fsub/fmul/fdiv/fsqrt/fcmp + fsave/frestore 1024 times; d0 != 0 on error'),  # 01004000.py
    0x01005ea0: ('ncc_cache_data_test', 'Nitro NCC: size from NCC bits4:3, test $03F00000 data RAM AA/55/pattern; d0 = fail addr or 0'),  # 01004000.py
    0x01006018: ('post_cache_tag_test', 'NCC cache tag RAM walking-pattern test (16 rotations of $D32B6D5B), prints failure; ret 0 ok / addr'),  # 01006000.py
    0x010060d6: ('post_cache_clear', 'zero NCC cache tag RAM $03E00000 and data RAM $03F00000 (size from NCC reg bits 4:3); no caller found'),  # 01006000.py
    0x0100610c: ('boot_cmd', "parse 'b [dev(ctrl,unit,part)] [file] [flags]' (default from NVRAM), run device open/load, ret entry pc"),  # 01006000.py
    0x01006300: ('boot_cmd_paren_check', "NOT a routine: middle of boot_cmd (bne after cmpi ')'); false pointer at $01007894"),  # 01006000.py
    0x01006560: ('boot_case_ok', "boot_cmd switch case 0: device opened, select 'Loading from ...' animation ($10 of dev entry)"),  # 01006000.py
    0x01006566: ('boot_case_flip_disk', "boot_cmd switch case 2: animation $13 of dev entry (od: 'Please flip disk')"),  # 01006000.py
    0x0100657a: ('boot_case_insert_disk', "boot_cmd switch case 3: animation $12 of dev entry (od: 'Please insert disk')"),  # 01006000.py
    0x0100658c: ('boot_case_no_media', "boot_cmd switch case 1: optical drive absent -> replace boot command by 'en' and restart"),  # 01006000.py
    0x0100660c: ('boot_cmd_diag_check_tail', "NOT a routine: tail of boot_cmd after strcmp(file,'diagnostics'); false pointer hits"),  # 01006000.py
    0x01006612: ('boot_cmd_reload_default', 'NOT a routine: boot_cmd path that reloads NVRAM boot command and restarts the parse'),  # 01006000.py
    0x0100662a: ('boot_case_error', "boot_cmd switch case 4/default: 'Bad disk/network' animation, od eject, wait 3 s, retry open"),  # 01006000.py
    0x0100670a: ('boot_l3_isr', 'level-3 ISR body: SCSI intr -> mg+$302 hook; video frame intr -> ack (per mg+$3BE) and animate'),  # 01006000.py
    0x010067e0: ('boot_l3_isr_tmc_tail', 'NOT a routine: Turbo branch of boot_l3_isr: TMC $02200080 := $05000000, animate, := $06000000'),  # 01006000.py
    0x0100680c: ('boot_anim_step', 'advance boot panel animation: draw text/icon of table entry mg+$2FA, count down mg+$2FE, poll keyboard'),  # 01006000.py
    0x010068ba: ('boot_l3_isr_entry_link', 'unused link.w prologue in front of boot_l3_isr_entry (compiler artifact)'),  # 01006000.py
    0x010068be: ('boot_l3_isr_entry', 'vector $6C (level-3 autovector) wrapper: save d0-d1/a0-a1, jsr boot_l3_isr, rte'),  # 01006000.py
    0x010068d2: ('boot_anim_set', 'select animation sequence n (entry $0101A354+10n) into mg+$2FA/$2FE and install boot_anim_step at mg+$30E'),  # 01006000.py
    0x01006914: ('boot_load_image_header', 'parse a.out $0107 or Mach-O FEEDFACE/MH_PRELOAD header in buf, copy first chunk, ret bytes left'),  # 01006000.py
    0x010069cc: ('enet_boot_open', 'en ops[0]: alloc $73C-byte netboot state (dev+$20), server MAC=broadcast, enet_init; ret 0 ok / 4'),  # 01006000.py
    0x01006a2e: ('enet_boot_close', 'en ops[1]: call netif devops[1] (enet shutdown)'),  # 01006000.py
    0x01006a44: ('tftp_load_kernel', 'en ops[2]: BOOTP then TFTP RRQ (octet) of the boot file, load via image header, ret entry pc'),  # 01006000.py
    0x01006e12: ('bootp_request', "broadcast BOOTP request (ports 68->67, vendor 'NeXT'), retry w/ backoff, handle NeXT login prompt"),  # 01006000.py
    0x010071ec: ('net_arp_reply', 'answer an ARP request for our IP: swap addresses, op=2, send through netif devops[3]'),  # 01006000.py
    0x010072a8: ('net_send_ip', 'build ethernet+IP header (type $800, dst MAC state+$22, src state+$1C), checksum, pad to 60, send'),  # 01006000.py
    0x01007354: ('net_poll_recv', 'netif read into state buffer; answer ARP; ret frame length if IP frame addressed to us else 0'),  # 01006000.py
    0x0100743c: ('net_ip_checksum', '16-bit ones-complement sum over len bytes (IP/UDP checksum, caller inverts)'),  # 01006000.py
    0x01007480: ('con_putc_crlf', 'putc with CR inserted before LF (console)'),  # 01006000.py
    0x010074b2: ('vid_draw_char', 'draw glyph c from font metrics $0101A4D0+6c at cursor mg+$1CE/$1D2 (bpp mg+$324); LF = newline'),  # 01006000.py
    0x0100766e: ('print_char_sink', 'printf output: dest 0 console, 1 screen text, 2 log buffer mg+$320 (or console), else string ptr'),  # 01006000.py
    0x010076d2: ('print_number', 'print unsigned/signed number in base with zero-pad/width to sink; args val,base,zero,width,sink'),  # 01006000.py
    0x01007772: ('printf', 'printf(fmt,...) to the console (vprintf dest 0)'),  # 01006000.py
    0x0100778a: ('sprintf', 'sprintf(buf,fmt,...) (vprintf with dest = buf)'),  # 01006000.py
    0x010077a4: ('vid_printf_at', 'clear boot panel text area (opt) and print fmt at screen x,y (dest 1, sets mg+$1CE/$1D2)'),  # 01006000.py
    0x0100785c: ('printf_log', 'printf(fmt,...) to dest 2: verbose log buffer mg+$320, or console when mg+$170 bit3 set'),  # 01006000.py
    0x01007876: ('vprintf', 'format engine: %% %0 %1-9 %D %d %u %O %o %X %x %c %l %s %b(BSD bit names); args fmt,dest,argp'),  # 01006000.py
    0x010078d6: ('vprintf_case_zero', 'vprintf case %0: set zero-pad flag'),  # 01006000.py
    0x010078da: ('vprintf_case_width', 'vprintf case %1..%9: accumulate field width'),  # 01006000.py
    0x010078e0: ('vprintf_case_hex', 'vprintf case %x/%X: base 16'),  # 01006000.py
    0x010078e4: ('vprintf_case_dec', 'vprintf case %d/%D/%u: base 10'),  # 01006000.py
    0x010078e8: ('vprintf_case_oct', 'vprintf case %o/%O: base 8'),  # 01006000.py
    0x01007904: ('vprintf_case_c', 'vprintf case %c: prints the 4 bytes of the long, high to low, non-zero 7-bit chars'),  # 01006000.py
    0x01007926: ('vprintf_case_b', 'vprintf case %b: value + BSD-style bit/field description string (base byte, <BIT,..>)'),  # 01006000.py
    0x01007b06: ('vprintf_case_s', 'vprintf case %s'),  # 01006000.py
    0x01007b24: ('vprintf_case_pct', 'vprintf case %%'),  # 01006000.py
    0x01007b38: ('print_line', 'printf(s) followed by newline'),  # 01006000.py
    0x01007b5c: ('con_gets', 'read a line (buf,size,echo): ^H/DEL erase, ^U kill, ^W word erase, CR/LF end; ret len+1, -1 on $FF'),  # 01006000.py
    0x01007ca8: ('str_skip_space', 'skip spaces, tabs, CR, LF; ret pointer to first other char'),  # 01006000.py
    0x01007cd8: ('parse_number', 'parse [-][~](0t|0x)digits[.digits..] into *out (dotted = byte-packed); base 0 = mg+$192; ret ptr/0'),  # 01006000.py
    0x01007dd6: ('mem_alloc', 'mg_alloc(n): mg+$EC (alloc_brk) -= n, bzero, ret pointer (installed at mg+$2EA)'),  # 01006000.py
    0x01007e0c: ('abs_l', 'abs(long); missed by the descent ($01007e06..$01007e15 mis-decoded as a string)'),  # 01008000.py
    0x01007e16: ('mem_cmp', 'bcmp(a,b,n): ret 0 equal, 1 different (long-wise when aligned)'),  # 01006000.py
    0x01007ec8: ('mem_move', 'bcopy(src,dst,n) with overlap handling (byte loops; the long fast path at +$26 is dead code)'),  # 01006000.py
    0x01007ffc: ('mem_zero', 'bzero(p,n): byte-align then long clears'),  # 01006000.py
    0x0100807c: ('str_index', 'index(s,c): ptr to first c in s (c==0 -> ptr to terminator), 0 if absent'),  # 01008000.py
    0x010080a2: ('str_ncpy', 'strncpy(dst,src,n); zero-pads; returns dst'),  # 01008000.py
    0x010080c2: ('str_cat', 'strcat(dst,src); returns dst'),  # 01008000.py
    0x010080d8: ('str_cmp', 'strcmp(a,b); returns a[i]-b[i] or 0'),  # 01008000.py
    0x010080f8: ('str_cpy', 'strcpy(dst,src); returns dst'),  # 01008000.py
    0x01008108: ('str_ncmp', 'strncmp(a,b,n)'),  # 01008000.py
    0x01008130: ('str_len', 'strlen(s)'),  # 01008000.py
    0x01008140: ('con_getc', 'mg_getc: read char from console selected by mg+$318 (0 kbd,1 SCC A,2 SCC B)'),  # 01008000.py
    0x01008184: ('con_try_getc', "mg_try_getc: non-blocking 'key pressed?' on console mg+$318; returns 1/0"),  # 01008000.py
    0x010081c8: ('con_putc', 'mg_putc(c): write char to console mg+$31C (0 screen,1 SCC A,2 SCC B)'),  # 01008000.py
    0x0100822c: ('delay_1us', 'delay_us(1); bit-bang half-clock spacing for the RTC'),  # 01008000.py
    0x0100823e: ('rtc_wait_tick', 'poll RTC seconds byte (reg $20 old / $23 new chip) until it changes'),  # 01008000.py
    0x0100828c: ('rtc_modify_reg', 'rtc_modify(reg,mask,val): read reg, clear mask bits, or (val&mask), write'),  # 01008000.py
    0x010082ca: ('rtc_power_int_handler', 'while INT_POWER($02007000 bit2): read status $30, ack LBAT/alarm/pdown; ret 1 if pdown'),  # 01008000.py
    0x01008380: ('rtc_power_down', 'wait tick, delay 850ms, set POWERDOWN bit in reg $31 (new) / $32 (old); spin forever'),  # 01008000.py
    0x010083d4: ('rtc_int_clear', 'old chip: write intctrl $32=0; then rtc_power_int_handler'),  # 01008000.py
    0x01008400: ('rtc_start_clock', 'rtc_int_clear; new chip: reg $31 |= $80 START; old chip: reg $31 = $B0'),  # 01008000.py
    0x01008440: ('time_tm_to_secs', 'convert {sec,min,hour,mday,mon,year} to seconds since 1970 (table dat_0101a8a2)'),  # 01008000.py
    0x010084d6: ('rtc_get_time', 'returns unix seconds: 0 if FIRSTUP; new chip 32-bit counter $20..$23; old chip BCD regs'),  # 01008000.py
    0x010085ec: ('bcd_to_bin', 'BCD byte -> binary'),  # 01008000.py
    0x0100861c: ('nvram_read', 'read RTC RAM regs 0..31 into buf, verify checksum word at +$1E; returns 0 ok / -1'),  # 01008000.py
    0x0100866c: ('nvram_write', 'compute checksum, write 32 RTC RAM regs ($80|i), read back and compare; 0 ok / -1'),  # 01008000.py
    0x010086e8: ('rtc_write_reg', 'rtc_write(reg,val): bit-bang addr|$80 then val, MSB first, via SCR2 RTCE/RTCLK/RTDATA'),  # 01008000.py
    0x01008790: ('rtc_read_regs', 'read n consecutive RTC regs starting at reg into buf'),  # 01008000.py
    0x010087cc: ('rtc_read_reg', 'rtc_read(reg) -> unsigned byte (wrapper of rtc_read_reg_raw)'),  # 01008000.py
    0x010087e8: ('rtc_read_reg_raw', 'bit-bang: send 8 addr bits, clock in 8 data bits from SCR2 bit $400'),  # 01008000.py
    0x0100889c: ('timer_read_us', 'read 20-bit us counter $0211A000..3, extend to 32 bits with mg+$2F6 wrap tracking'),  # 01008000.py
    0x0100890e: ('timer_read_ms', 'timer_read_us()/1000'),  # 01008000.py
    0x01008924: ('timer_elapsed_us', 'timer_read_us() - t0'),  # 01008000.py
    0x01008936: ('delay_us', 'busy-wait n microseconds on the event counter (n+1 ticks)'),  # 01008000.py
    0x01008964: ('scc_init', 'WR9=$C0 hw reset, then scc_init_channel(A,9600), (B,9600); clears mg+4 bits 4,5'),  # 01008000.py
    0x010089cc: ('scc_init_channel', 'program WR9,11,0,4,3,5,14,12,13,14,3,5 for 8N1 x16 BRG at baud (arg2)'),  # 01008000.py
    0x01008b30: ('scc_calc_baud_tc', 'SCC clock reg $02118004=$0A; pick PCLK 3.6864M or RTxC 4M, return TC|$20000 if PCLK'),  # 01008000.py
    0x01008bce: ('scc_getc_raw', 'wait RR0 bit0 (Rx char available) then read data reg ctrl+2'),  # 01008000.py
    0x01008be8: ('scc_putc_raw', 'wait RR0 bit2 (Tx buffer empty) then write data reg ctrl+2'),  # 01008000.py
    0x01008c04: ('scc_rx_ready', 'return RR0 & 1'),  # 01008000.py
    0x01008c1a: ('scc_poll_flow_control', 'if rx char: XOFF($13) sets mg+4 bit5, XON($11) clears it, other sets bit4'),  # 01008000.py
    0x01008c72: ('scc_getc', 'init SCC if mg+4 bit6 clear; read char (skip XON/XOFF), clear bit4, return c&$7F'),  # 01008000.py
    0x01008cd6: ('scc_try_getc', 'return mg+4 bit4 (char seen while polling) and clear it'),  # 01008000.py
    0x01008cf4: ('scc_putc', 'init if needed; honour XOFF; add even parity (table $0101A8BC); scc_putc_raw'),  # 01008000.py
    0x01008d68: ('scc_stub_ret0', 'empty SCC ops entry, returns 0 (slots 0,1 of table $0101A944)'),  # 01008000.py
    0x01008d74: ('enet_reg_read', "bus-error-safe byte read, 15 retries; prints 'enreg_read failed'"),  # 01008000.py
    0x01008dc0: ('enet_reg_write', "bus-error-safe byte write, 15 retries; prints 'enreg_write failed'"),  # 01008000.py
    0x01008e0a: ('enet_reg_poll', 'bus-error-safe read, up to 10 tries 1ms apart; returns 1 ok / 0 fail'),  # 01008000.py
    0x01008e56: ('enet_nop', 'empty netif op (slot 4 of table $0101A95C)'),  # 01008000.py
    0x01008e5e: ('enet_init', 'netif init: alloc state, carve 33x8KB buffers, reset chip, MAC, masks, RX DMA, vec 30'),  # 01008000.py
    0x010090fe: ('enet_isr_dead_prologue', 'stray link a6 before enet_rx_isr; not a real routine'),  # 01008000.py
    0x01009102: ('enet_rx_isr', 'autovector 30 (level 6) stub: save d0-d1/a0-a1, call enet_rx_int, rte'),  # 01008000.py
    0x01009116: ('enet_read', 'netif read(buf,max): pop next received ring entry, Turbo +1 byte realign, return len'),  # 01008000.py
    0x0100928a: ('enet_write', 'netif write(buf,len,tpcheck): TX DMA one packet, wait ready/complete, TP fallback'),  # 01008000.py
    0x010095b2: ('enet_close', 'TX/RX DMA CSR = DMA_RESET, control reg $02106006 = $80 (chip reset)'),  # 01008000.py
    0x010095f0: ('enet_rx_int', 'RX DMA interrupt: record CSR/status/saved limit ($02004050) in ring, restart DMA'),  # 01008000.py
    0x010096be: ('enet_rx_dma_start', 'chain next 8KB buffer into RX DMA (next/limit/start/stop), CSR cmd, RX mode on'),  # 01008000.py
    0x01009860: ('kms_send_reset', 'SR=$2700, $0200E002|=1, KMS cmd $C6 data $1000A825 (magic reset) then $C6/0'),  # 01008000.py
    0x010098a4: ('kms_console_init', 'probe keyboard via $C5/$EF000000; no kbd + NVRAM altcons -> console=SCC A; text init'),  # 01008000.py
    0x010099e6: ('vid_text_reset', 'reset text window: colours, cursor col/row=0, mg+$166=&mg+$16C, clear $16A.., $1CE'),  # 01008000.py
    0x01009a2c: ('vid_draw_panel', 'draw ROM monitor alert panel (title, w chars, h lines) in 1/2/8/16/32bpp, save under $158'),  # 01008000.py
    0x01009e9a: ('vid_restore_panel', 'copy saved pixels from mg+$158 back to the framebuffer, clear $158, cursor on'),  # 01008000.py
    0x01009fde: ('mon_clear_nmi', 'ack NMI: $0200E001 |= $10 (NMI_RECEIVED), Turbo: clear TMC NMI reg $02200020'),  # 01008000.py
    0x0100a00e: ('kms_poll_km_event', 'poll KMS $0200E000: if KM data received (bit22/21) latch $0200E008 in mg+$144, set mg_flags bit1; ret 1'),  # 0100a000.py
    0x0100a06c: ('kms_event_pending', 'ret 1 if a KM event is latched (mg_flags bit1, cleared) or dequeued from the int queue when mg+$3E5 bit0'),  # 0100a000.py
    0x0100a0ac: ('con_flow_control_poll', 'poll keyboard during output: ^S sets mg+$170 bit2 (pause), ^Q clears it, other key sets mg_flags bit0'),  # 0100a000.py
    0x0100a118: ('vid_console_putc', 'graphics-console putc: init KMS/console if needed, honour ^S/^Q, LF->CRLF, vid_putc'),  # 0100a000.py
    0x0100a1a8: ('kms_power_key_check', "if INT_POWER pending: ask 'really power down?' and power off on y; else dequeue+translate key (int mode)"),  # 0100a000.py
    0x0100a2ba: ('kms_read_key', 'read one key: int-queue mode or polled (KMPOLL cmd $C6 data $01FFFFF6, KMREG $C5 $EF000000 on no-response)'),  # 0100a000.py
    0x0100a3a6: ('vid_console_getc', 'console getc: loop kms_read_key until a real char, CR->LF'),  # 0100a000.py
    0x0100a3f2: ('kms_translate_key', 'KM event -> ASCII via keymap $0101A978 (shift/ctrl); $101/$107 = brightness down/up; $100 = none'),  # 0100a000.py
    0x0100a47c: ('kms_key_brightness', 'brightness key: NVRAM bits 19:14 +/-1 (0..$3D), nvram write, driver op +$18 (palette rescale)'),  # 0100a000.py
    0x0100a4da: ('kms_send_cmd_wait', 'kms_send_cmd then wait <=100000 polls for $0200E001 bit6 KM_RECEIVED; ret $40000000 on timeout'),  # 0100a000.py
    0x0100a520: ('kms_send_cmd_0100a520', 'enable KMS ($0200E002 |= 2, once, mg+$170 bit7), write cmd byte $0200E003 and data long $0200E004, 100us'),  # 0100a000.py
    0x0100a56c: ('vid_clear_text_area', 'fill the text window (rows mg+$150..+$156, cols $152..+$154, 8x12 cells) with bg pixel mg+$160'),  # 0100a000.py
    0x0100a5fa: ('vid_clear_screen', 'fill whole frame buffer (mg+$368, $328*$334 bytes) with mg+$344 (dark grey $55505550 / mono $AAAAAAAA)'),  # 0100a000.py
    0x0100a63c: ('vid_putc', 'draw char at cursor (mg+$14C col,$14E row) 8x12 font $0101AC00, 2/8/16/32 bpp paths, scroll at bottom'),  # 0100a000.py
    0x0100a678: ('vid_putc_cr', 'vid_putc case CR: col=0 (draws cursor first if mg+$170 bit8 clear)'),  # 0100a000.py
    0x0100a69c: ('vid_putc_lf', 'vid_putc case LF: row++'),  # 0100a000.py
    0x0100a6a4: ('vid_putc_bs', 'vid_putc case BS: col-- if >0'),  # 0100a000.py
    0x0100a6b4: ('vid_putc_tab', 'vid_putc case TAB: spaces to next multiple of 8'),  # 0100a000.py
    0x0100a6f2: ('vid_putc_ff', 'vid_putc case FF: cursor home + vid_clear_text_area'),  # 0100a000.py
    0x0100a704: ('vid_putc_bel', 'vid_putc case BEL: sub_01005758(1) then (0) = beep on/off'),  # 0100a000.py
    0x0100a71a: ('vid_putc_glyph', 'vid_putc printable path: 12 font rows, pixels-per-long switch (16=2bpp,4=8bpp,2=16bpp,1=32bpp)'),  # 0100a000.py
    0x0100a8b2: ('vid_putc_advance', 'vid_putc epilogue: wrap col/row, scroll one text line (12 scanlines) when row>=rows'),  # 0100a000.py
    0x0100a94c: ('vid_scroll_copy_31', "scroll copy entry: copies 31 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a94e: ('vid_scroll_copy_30', "scroll copy entry: copies 30 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a950: ('vid_scroll_copy_29', "scroll copy entry: copies 29 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a952: ('vid_scroll_copy_28', "scroll copy entry: copies 28 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a954: ('vid_scroll_copy_27', "scroll copy entry: copies 27 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a956: ('vid_scroll_copy_26', "scroll copy entry: copies 26 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a958: ('vid_scroll_copy_25', "scroll copy entry: copies 25 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a95a: ('vid_scroll_copy_24', "scroll copy entry: copies 24 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a95c: ('vid_scroll_copy_23', "scroll copy entry: copies 23 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a95e: ('vid_scroll_copy_22', "scroll copy entry: copies 22 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a960: ('vid_scroll_copy_21', "scroll copy entry: copies 21 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a962: ('vid_scroll_copy_20', "scroll copy entry: copies 20 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a964: ('vid_scroll_copy_19', "scroll copy entry: copies 19 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a966: ('vid_scroll_copy_18', "scroll copy entry: copies 18 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a968: ('vid_scroll_copy_17', "scroll copy entry: copies 17 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a96a: ('vid_scroll_copy_16', "scroll copy entry: copies 16 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a96c: ('vid_scroll_copy_15', "scroll copy entry: copies 15 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a96e: ('vid_scroll_copy_14', "scroll copy entry: copies 14 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a970: ('vid_scroll_copy_13', "scroll copy entry: copies 13 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a972: ('vid_scroll_copy_12', "scroll copy entry: copies 12 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a974: ('vid_scroll_copy_11', "scroll copy entry: copies 11 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a976: ('vid_scroll_copy_10', "scroll copy entry: copies 10 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a978: ('vid_scroll_copy_9', "scroll copy entry: copies 9 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a97a: ('vid_scroll_copy_8', "scroll copy entry: copies 8 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a97c: ('vid_scroll_copy_7', "scroll copy entry: copies 7 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a97e: ('vid_scroll_copy_6', "scroll copy entry: copies 6 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a980: ('vid_scroll_copy_5', "scroll copy entry: copies 5 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a982: ('vid_scroll_copy_4', "scroll copy entry: copies 4 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a984: ('vid_scroll_copy_3', "scroll copy entry: copies 3 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a986: ('vid_scroll_copy_2', "scroll copy entry: copies 2 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a988: ('vid_scroll_copy_1', "scroll copy entry: copies 1 longs then falls into the 32-long loop (Duff's device in vid_putc)"),  # 0100a000.py
    0x0100a98a: ('vid_scroll_copy_0', 'Duff-device tail of the scroll copy (entry for 0 longs; loops 32 longs per pass)'),  # 0100a000.py
    0x0100a9ce: ('vid_cursor_toggle', 'invert the 8x12 cell at the cursor (not.l / not.w per pixel-long) if col>=0'),  # 0100a000.py
    0x0100aa76: ('vid_clear_to_eol', 'fill from cursor col to end of the current text row (12 scanlines) with bg mg+$160/$162'),  # 0100a000.py
    0x0100ab1e: ('mon_alert_printf', 'open the console/alert window (sub_01009a2c(x,y,title)) if mg+$170 bit3 clear, set bit5, printf(fmt,...)'),  # 0100a000.py
    0x0100ab7c: ('mon_boot_error', "mg+$2E2 slot: mon_alert_printf(0,0,'Error during boot', fmt, a,b,c)"),  # 0100a000.py
    0x0100aba4: ('mon_alert_close', 'if mg+$170 bit5: sub_01009e9a (close window), mg_flags |= 8, clear bit5'),  # 0100a000.py
    0x0100abdc: ('nbus_rom_read_long', 'read long #n of the slot board config ROM (mg+$35C) honouring byte-lane width mg+$34E (1/4/8)'),  # 0100a000.py
    0x0100ac8a: ('vid_console_init', 'boot display select: probe on-board drivers, init+DAC+clear, NextBus slot scan on cubes, NVRAM console slot'),  # 0100a000.py
    0x0100ae26: ('nbus_probe_display_board', 'probe slot n: NBIC id $F0FFFFF0, magic $A5 at $F0FFFFE0, run board ROM display code; ret 1 if display'),  # 0100a000.py
    0x0100b012: ('vid_post_init', "slot board: run board 'enable' code (ROM long 2*idx+3); on-board: vid_enable_display"),  # 0100a000.py
    0x0100b04e: ('vid_init_display', '(mg,slot,idx): on-board -> vid_driver_init; else build display struct mg+$324 from board ROM'),  # 0100a000.py
    0x0100b2b2: ('vid_lock', '++mg+$3A0; on first level: on-board driver op +$10 (nop for built-in displays) or run board code mg+$350'),  # 0100a000.py
    0x0100b2f4: ('vid_unlock', '--mg+$3A0; at zero: on-board driver op +$14 (cpusha for colour, nop for mono) or run board code mg+$354'),  # 0100a000.py
    0x0100b338: ('nbus_map_addr', 'map a NextBus board address through the 6 windows mg+$358+12*i {bus,cpu,size}'),  # 0100a000.py
    0x0100b38c: ('nbus_run_boardcode', 'interpreter for NeXTbus board ROM display code (8 regs, opcode bits 31:26, 0x2A ops); ret r0'),  # 0100a000.py
    0x0100b3b0: ('nbus_op_next', 'nbus_run_boardcode fetch/dispatch loop'),  # 0100a000.py
    0x0100b3ee: ('nbus_op_ldi', 'op $20: r[d] = imm'),  # 0100a000.py
    0x0100b3fe: ('nbus_op_ldmem_imm', 'op $21: r[d] = *map(imm | slot)'),  # 0100a000.py
    0x0100b41e: ('nbus_op_ldmem_reg', 'op $01: r[d] = *map(r[s] | slot)'),  # 0100a000.py
    0x0100b468: ('nbus_op_stmem_imm', 'op $22: *map(imm | slot) = r[s]'),  # 0100a000.py
    0x0100b488: ('nbus_op_stmem_reg', 'op $02: *map(r[s] | slot) = r[t]'),  # 0100a000.py
    0x0100b4d2: ('nbus_op_block_store', 'op $03: n = ins&$3FFFFFF pairs (value, addr): *map(addr|slot) = value'),  # 0100a000.py
    0x0100b528: ('nbus_op_addi', 'op $24: r[d] = r[s] + imm'),  # 0100a000.py
    0x0100b54a: ('nbus_op_add', 'op $04: r[d] = r[s] + r[t]'),  # 0100a000.py
    0x0100b576: ('nbus_op_subi', 'op $25: r[d] = r[s] - imm'),  # 0100a000.py
    0x0100b598: ('nbus_op_rsubi', 'op $26: r[d] = imm - r[s]'),  # 0100a000.py
    0x0100b5ba: ('nbus_op_sub', 'op $05: r[d] = r[s] - r[t]'),  # 0100a000.py
    0x0100b5e6: ('nbus_op_andi', 'op $27: r[d] = r[s] & imm'),  # 0100a000.py
    0x0100b608: ('nbus_op_and', 'op $07: r[d] = r[s] & r[t]'),  # 0100a000.py
    0x0100b634: ('nbus_op_ori', 'op $28: r[d] = r[s] | imm'),  # 0100a000.py
    0x0100b656: ('nbus_op_or', 'op $08: r[d] = r[s] | r[t]'),  # 0100a000.py
    0x0100b682: ('nbus_op_xori', 'op $29: r[d] = r[s] ^ imm'),  # 0100a000.py
    0x0100b6a4: ('nbus_op_xor', 'op $09: r[d] = r[s] ^ r[t]'),  # 0100a000.py
    0x0100b6d2: ('nbus_op_shl', 'op $0A: r[d] = r[s] << (ins>>16 & 31)'),  # 0100a000.py
    0x0100b6fc: ('nbus_op_asr', 'op $0B: r[d] = r[s] >> (ins>>16 & 31) arithmetic'),  # 0100a000.py
    0x0100b726: ('nbus_op_mov', 'op $0C: r[d] = r[s]'),  # 0100a000.py
    0x0100b744: ('nbus_op_test', 'op $06: set zero/pos/neg flags (a3/a5/a4) from r[s]'),  # 0100a000.py
    0x0100b776: ('nbus_op_bgt', 'op $0E: jump to ins&$3FFFFFF if pos'),  # 0100a000.py
    0x0100b77e: ('nbus_op_blt', 'op $0F: jump if neg'),  # 0100a000.py
    0x0100b786: ('nbus_op_beq', 'op $10: jump if zero'),  # 0100a000.py
    0x0100b78e: ('nbus_op_ble', 'op $11: jump if !pos'),  # 0100a000.py
    0x0100b796: ('nbus_op_bge', 'op $12: jump if !neg'),  # 0100a000.py
    0x0100b79e: ('nbus_op_bne', 'op $13: jump if !zero'),  # 0100a000.py
    0x0100b7a4: ('nbus_op_jump', 'op $0D (and taken branches): pc = ins & $3FFFFFF'),  # 0100a000.py
    0x0100b7b0: ('nbus_op_return', 'op $00: return r0'),  # 0100a000.py
    0x0100b7c0: ('vid_find_driver', 'call probe(mg) of the 3 display drivers ($0101B080, 28 bytes each); ret first index answering 1, else -1'),  # 0100a000.py
    0x0100b802: ('vid_enable_display', 'clamp NVRAM brightness to >= $14 (nvram write); on-board display: driver op +$C (palette + video enable)'),  # 0100a000.py
    0x0100b85c: ('vid_driver_init', '(mg,idx): bzero mg+$324..$3A3, call driver[idx] init(mg,idx)'),  # 0100a000.py
    0x0100b8a6: ('vid_driver_setup_dac', 'on-board display: driver op +8 (dac_init_bt463 for colour, nop for mono)'),  # 0100a000.py
    0x0100b8d8: ('vid_driver_enter', 'on-board display: driver op +$10 (sub_0100c1aa nop for all built-in displays)'),  # 0100a000.py
    0x0100b90a: ('vid_driver_exit', 'on-board display: driver op +$14 (colour: sub_010040a8 cpusha; mono: nop)'),  # 0100a000.py
    0x0100b93c: ('vid_driver_set_brightness', '(mg,val): on-board display: driver op +$18 (colour: palette rescale; mono: $02110000 register)'),  # 0100a000.py
    0x0100b972: ('vid_probe_color_1120', 'driver 0 probe: type 3 -> 1; types 5,7,9,B -> SCR2 byte2 bit4 (video mode) set; else 0'),  # 0100a000.py
    0x0100b994: ('vid_probe_scr2_vidmode', "ret 1 if SCR2 $0200D002 bit4 set (Previous: 'video mode is 25 MHz'), else 0"),  # 0100a000.py
    0x0100b99e: ('vid_probe_yes', 'ret 1'),  # 0100a000.py
    0x0100b9a2: ('vid_probe_no', 'ret 0'),  # 0100a000.py
    0x0100b9a8: ('vid_probe_color_832', 'driver 1 probe: types 5,7,9,B with SCR2 byte2 bit4 clear -> 1 (832x624 colour mode)'),  # 0100a000.py
    0x0100b9e6: ('vid_init_color_1120x832', 'display struct: 2 px/long (16bpp), 2240 B/line, 1120x832, VRAM $0C000000 (Turbo)/$2C000000, greys FFF0/AAA0/5550/0'),  # 0100a000.py
    0x0100bb8e: ('vid_init_color_832x624', 'display struct: 16bpp, 1664 B/line, 832x624, VRAM $0C000000/$2C000000, same grey values'),  # 0100a000.py
    0x0100bc78: ('dac_init_bt463', 'Bt463 $0201C000 (Turbo)/$02118100: CR0=40 CR1=0 CR2=80 readmask F0x4 blink 0x4, WTT[16]=000100, gamma palette, ovl FF'),  # 0100a000.py
    0x0100be7c: ('vid_color_enable', 'driver op +$C colour: palette from NVRAM brightness, then TMC $02200080=$04000000 (Turbo) / $02118180=4'),  # 0100a000.py
    0x0100bebe: ('dac_set_brightness_palette', '(mg,bright): Bt463 palette 0..255 = min(255, gamma[i]*(bright*64/61)/64 + 8), R=G=B'),  # 0100a000.py
    0x0100bf72: ('vid_probe_mono', 'driver 2 probe: types 4,6,8,A -> 1; 3,5,7,9,B -> 0; other types -> 1'),  # 0100a000.py
    0x0100bf94: ('vid_probe_mono_no', 'ret 0 (colour type)'),  # 0100a000.py
    0x0100bf98: ('vid_probe_mono_yes', 'ret 1'),  # 0100a000.py
    0x0100bf9e: ('vid_init_mono_1120x832', 'display struct: 16 px/long (2bpp), 280 B/line (288 non-Turbo), 1120x832, VRAM $0C000000/$0B000000'),  # 0100a000.py
    0x0100c146: ('vid2_nop_m2', 'video driver 2 method 2: empty (link/unlk/rts)'),  # 0100c000.py
    0x0100c14e: ('vid2_enable', 'vid drv 2 method 3: brightness reg $02110000 = LFSR(ni_brightness)|$40; Turbo: TMC video intr reg = $04 (enable)'),  # 0100c000.py
    0x0100c18a: ('vid2_set_brightness', 'vid drv 2 method 6 (mg, level): $02110000 = brightness_lfsr_tab[level] | $40'),  # 0100c000.py
    0x0100c1aa: ('vid_nop', 'empty method shared by video driver vectors (link/unlk/rts)'),  # 0100c000.py
    0x0100c1b4: ('adb_init', 'reset ADB bus, probe addr 1..7 (talk reg 3), build device chain at mg+$3e6, init kbd(2)/mouse(3), start talk reg0'),  # 0100c000.py
    0x0100c2c2: ('adb_intr', 'ADB interrupt service (unreferenced): ack INTSTATUS, CTRL=$10, read DATA0/1, call handler tab 0101b114, re-poll'),  # 0100c000.py
    0x0100c398: ('adb_kbd_poll', '(buf): ack ADB int, if ACCESS+DATAPEND for dev 2 copy DATA0/1 to buf; send talk addr2 reg0; delay 8000; ret 1=data'),  # 0100c000.py
    0x0100c458: ('adb_reset_bus', '(wait): ack INTSTATUS, CTRL=$08 RESET_ADB; if wait spin on INTSTATUS bit3 then write 8 to clear'),  # 0100c000.py
    0x0100c482: ('adb_send_cmd', '(cmdbyte,dataptr,len,wait): CMD=addr<<4|cmd<<2|reg, DATA0/1, COUNT=len*8, CTRL=$04 XMIT; wait ACCESS int, clear'),  # 0100c000.py
    0x0100c4fa: ('adb_talk', '(addr,reg,dataptr,countptr): TALK cmd (3) with wait; if STATUS bit3 DATAPEND read COUNT>>3 bytes from DATA0/1'),  # 0100c000.py
    0x0100c572: ('adb_listen', '(addr,reg,dataptr,len): LISTEN cmd (2) with wait via adb_send_cmd'),  # 0100c000.py
    0x0100c5a6: ('adb_kbd_raise_nmi', 'Turbo only: reset ADB bus, set TMC NMI reg $02200020 bit0 (raises NMI), delay 8000 us'),  # 0100c000.py
    0x0100c5e0: ('adb_set_config', '(flag) (unreferenced): CTRL=$10 RESET_WD; CONFIG = 3 (SYSTEM|WATCHDOG) if flag==1 and a device is current else 0'),  # 0100c000.py
    0x0100c626: ('adb_probe_kbd_alt_video', '(mg): mg+$3be=2, reset ADB, talk addr2 reg3; if kbd answers and SCR2 byte2 bit4: alt TMC timing by type 4..9'),  # 0100c000.py
    0x0100c68a: ('tmc_alt_timing_color', 'types 5,7,9: TMC horiz $02200088 = $29044118, vert $0220008c = $021A0340 (20/32/68/280, 1/3/32/832)'),  # 0100c000.py
    0x0100c6a4: ('tmc_alt_timing_mono', 'types 4,6,8: TMC horiz $02200088 = $5B02B118, vert $0220008c = $0041C340 (45/32/43/280, 0/8/28/832)'),  # 0100c000.py
    0x0100c6c4: ('adb_kbd_init', '(addr,buf): mg+$3e2|=1; listen reg3 handler=3; talk reg3; if handler 3: $3e2|=2, talk reg2, set caps state, listen reg2 LEDs'),  # 0100c000.py
    0x0100c788: ('adb_kbd_handler', '(data,count) ADB reg0 handler for addr 2 (tab 0101b114[2]): push 2 key events to ring mg+$486, translate to NeXT event mg+$144'),  # 0100c000.py
    0x0100c958: ('kbd_a_up_ctrl_l', 'ADB $36 ctrl release: clear mg+$48a bit7, recompute ctrl bit'),  # 0100c000.py
    0x0100c962: ('kbd_a_up_ctrl_r', 'ADB $7d right ctrl release: clear $48a bit6'),  # 0100c000.py
    0x0100c96c: ('kbd_a_up_cmd', 'ADB $37 command release: clear $48a bit3 and event bits $1000/$800'),  # 0100c000.py
    0x0100c986: ('kbd_a_up_shift_l', 'ADB $38 shift release: clear $200 (and $400 if not extended kbd)'),  # 0100c000.py
    0x0100c99e: ('kbd_a_up_shift_r', 'ADB $7b right shift release: clear $400'),  # 0100c000.py
    0x0100c9a8: ('kbd_a_up_alt_l', 'ADB $3a option release: clear $2000 (and $4000), clear $48a bit5'),  # 0100c000.py
    0x0100c9ce: ('kbd_a_up_alt_r', 'ADB $7c right option release: clear $4000 unless help held, clear $48a bit4'),  # 0100c000.py
    0x0100c9e6: ('kbd_a_up_capslock', 'ADB $39 caps lock release: clear $48a bits0-1, clear $400, update LEDs (listen reg2) if extended'),  # 0100c000.py
    0x0100ca3e: ('kbd_a_up_help', 'ADB $72 release: clear $48a bit2, clear $1000/$4000 unless cmd/alt_r held'),  # 0100c000.py
    0x0100ca82: ('kbd_a_down_ctrl_l', 'ADB $36 ctrl press: set $48a bit7, set event ctrl bit'),  # 0100c000.py
    0x0100ca8a: ('kbd_a_down_ctrl_r', 'ADB $7d right ctrl press: set $48a bit6'),  # 0100c000.py
    0x0100caac: ('kbd_a_down_cmd', 'ADB $37 command press: set $48a bit3, event |= $1000|$800'),  # 0100c000.py
    0x0100cac6: ('kbd_a_down_shift_l', 'ADB $38 shift press: set $200 (and $400 if not extended)'),  # 0100c000.py
    0x0100cade: ('kbd_a_down_shift_r', 'ADB $7b right shift press: set $400'),  # 0100c000.py
    0x0100cae8: ('kbd_a_down_alt_l', 'ADB $3a option press: set $2000 (and $4000 if not extended), $48a bit5'),  # 0100c000.py
    0x0100cb06: ('kbd_a_down_alt_r', 'ADB $7c right option press: set $4000, $48a bit4'),  # 0100c000.py
    0x0100cb14: ('kbd_a_down_capslock', 'ADB $39 caps lock press: $48a bit1, set $400, update LEDs if extended'),  # 0100c000.py
    0x0100cb74: ('kbd_a_down_help', 'ADB $72 press: $48a bit2, event |= $1000|$4000'),  # 0100c000.py
    0x0100cb8e: ('kbd_a_event_done', 'after modifier update: magic keys (0x25 reset via sub_01009860, 0x26 NMI), loop while ring not empty'),  # 0100c000.py
    0x0100cc06: ('adb_kbd_getevent_unused', '(evptr) duplicate of adb_kbd_getevent; no reference found'),  # 0100c000.py
    0x0100cd68: ('kbd_b_up_ctrl_l', 'copy of kbd_a_up_ctrl_l'),  # 0100c000.py
    0x0100cd72: ('kbd_b_up_ctrl_r', 'copy of kbd_a_up_ctrl_r'),  # 0100c000.py
    0x0100cd7c: ('kbd_b_up_cmd', 'copy of kbd_a_up_cmd'),  # 0100c000.py
    0x0100cd96: ('kbd_b_up_shift_l', 'copy of kbd_a_up_shift_l'),  # 0100c000.py
    0x0100cdae: ('kbd_b_up_shift_r', 'copy of kbd_a_up_shift_r'),  # 0100c000.py
    0x0100cdb8: ('kbd_b_up_alt_l', 'copy of kbd_a_up_alt_l'),  # 0100c000.py
    0x0100cdde: ('kbd_b_up_alt_r', 'copy of kbd_a_up_alt_r'),  # 0100c000.py
    0x0100cdf6: ('kbd_b_up_capslock', 'copy of kbd_a_up_capslock'),  # 0100c000.py
    0x0100ce4e: ('kbd_b_up_help', 'copy of kbd_a_up_help'),  # 0100c000.py
    0x0100ce92: ('kbd_b_down_ctrl_l', 'copy of kbd_a_down_ctrl_l'),  # 0100c000.py
    0x0100ce9a: ('kbd_b_down_ctrl_r', 'copy of kbd_a_down_ctrl_r'),  # 0100c000.py
    0x0100cebc: ('kbd_b_down_cmd', 'copy of kbd_a_down_cmd'),  # 0100c000.py
    0x0100ced6: ('kbd_b_down_shift_l', 'copy of kbd_a_down_shift_l'),  # 0100c000.py
    0x0100ceee: ('kbd_b_down_shift_r', 'copy of kbd_a_down_shift_r'),  # 0100c000.py
    0x0100cef8: ('kbd_b_down_alt_l', 'copy of kbd_a_down_alt_l'),  # 0100c000.py
    0x0100cf16: ('kbd_b_down_alt_r', 'copy of kbd_a_down_alt_r'),  # 0100c000.py
    0x0100cf24: ('kbd_b_down_capslock', 'copy of kbd_a_down_capslock'),  # 0100c000.py
    0x0100cf84: ('kbd_b_down_help', 'copy of kbd_a_down_help'),  # 0100c000.py
    0x0100cf9e: ('kbd_b_event_done', 'store event to *evptr, magic key check, return'),  # 0100c000.py
    0x0100d032: ('adb_kbd_getevent', '(evptr): drain ring or poll kbd; ADB code->NeXT keycode, modifiers; magic Cmd+Alt+* reset / Cmd+Alt+` NMI; ret 1 if event'),  # 0100c000.py
    0x0100d194: ('kbd_c_up_ctrl_l', 'copy of kbd_a_up_ctrl_l'),  # 0100c000.py
    0x0100d19e: ('kbd_c_up_ctrl_r', 'copy of kbd_a_up_ctrl_r'),  # 0100c000.py
    0x0100d1a8: ('kbd_c_up_cmd', 'copy of kbd_a_up_cmd'),  # 0100c000.py
    0x0100d1c2: ('kbd_c_up_shift_l', 'copy of kbd_a_up_shift_l'),  # 0100c000.py
    0x0100d1da: ('kbd_c_up_shift_r', 'copy of kbd_a_up_shift_r'),  # 0100c000.py
    0x0100d1e4: ('kbd_c_up_alt_l', 'copy of kbd_a_up_alt_l'),  # 0100c000.py
    0x0100d20a: ('kbd_c_up_alt_r', 'copy of kbd_a_up_alt_r'),  # 0100c000.py
    0x0100d222: ('kbd_c_up_capslock', 'copy of kbd_a_up_capslock'),  # 0100c000.py
    0x0100d27a: ('kbd_c_up_help', 'copy of kbd_a_up_help'),  # 0100c000.py
    0x0100d2be: ('kbd_c_down_ctrl_l', 'copy of kbd_a_down_ctrl_l'),  # 0100c000.py
    0x0100d2c6: ('kbd_c_down_ctrl_r', 'copy of kbd_a_down_ctrl_r'),  # 0100c000.py
    0x0100d2e8: ('kbd_c_down_cmd', 'copy of kbd_a_down_cmd'),  # 0100c000.py
    0x0100d302: ('kbd_c_down_shift_l', 'copy of kbd_a_down_shift_l'),  # 0100c000.py
    0x0100d31a: ('kbd_c_down_shift_r', 'copy of kbd_a_down_shift_r'),  # 0100c000.py
    0x0100d324: ('kbd_c_down_alt_l', 'copy of kbd_a_down_alt_l'),  # 0100c000.py
    0x0100d342: ('kbd_c_down_alt_r', 'copy of kbd_a_down_alt_r'),  # 0100c000.py
    0x0100d350: ('kbd_c_down_capslock', 'copy of kbd_a_down_capslock'),  # 0100c000.py
    0x0100d3b0: ('kbd_c_down_help', 'copy of kbd_a_down_help (table entry 010127cc)'),  # 0100c000.py
    0x0100d3ca: ('kbd_c_event_done', 'store event to *evptr, magic key check (reset/NMI), return'),  # 0100c000.py
    0x0100d5ee: ('kbd_d_up_ctrl_l', 'copy of kbd_a_up_ctrl_l'),  # 0100c000.py
    0x0100d5f8: ('kbd_d_up_ctrl_r', 'copy of kbd_a_up_ctrl_r'),  # 0100c000.py
    0x0100d602: ('kbd_d_up_cmd', 'copy of kbd_a_up_cmd'),  # 0100c000.py
    0x0100d61c: ('kbd_d_up_shift_l', 'copy of kbd_a_up_shift_l'),  # 0100c000.py
    0x0100d634: ('kbd_d_up_shift_r', 'copy of kbd_a_up_shift_r'),  # 0100c000.py
    0x0100d63e: ('kbd_d_up_alt_l', 'copy of kbd_a_up_alt_l'),  # 0100c000.py
    0x0100d664: ('kbd_d_up_alt_r', 'copy of kbd_a_up_alt_r'),  # 0100c000.py
    0x0100d67c: ('kbd_d_up_capslock', 'copy of kbd_a_up_capslock'),  # 0100c000.py
    0x0100d6d4: ('kbd_d_up_help', 'copy of kbd_a_up_help'),  # 0100c000.py
    0x0100d718: ('kbd_d_down_ctrl_l', 'copy of kbd_a_down_ctrl_l'),  # 0100c000.py
    0x0100d720: ('kbd_d_down_ctrl_r', 'copy of kbd_a_down_ctrl_r'),  # 0100c000.py
    0x0100d742: ('kbd_d_down_cmd', 'copy of kbd_a_down_cmd'),  # 0100c000.py
    0x0100d75c: ('kbd_d_down_shift_l', 'copy of kbd_a_down_shift_l'),  # 0100c000.py
    0x0100d774: ('kbd_d_down_shift_r', 'copy of kbd_a_down_shift_r'),  # 0100c000.py
    0x0100d77e: ('kbd_d_down_alt_l', 'copy of kbd_a_down_alt_l'),  # 0100c000.py
    0x0100d79c: ('kbd_d_down_alt_r', 'copy of kbd_a_down_alt_r'),  # 0100c000.py
    0x0100d7aa: ('kbd_d_down_capslock', 'copy of kbd_a_down_capslock'),  # 0100c000.py
    0x0100d80a: ('kbd_d_down_help', 'copy of kbd_a_down_help'),  # 0100c000.py
    0x0100d824: ('kbd_d_event_done', 'store event to *evptr, magic key check (reset/NMI), return'),  # 0100c000.py
    0x0100d8a6: ('adb_mouse_init', '(addr,buf): $3e2|=$10000; talk/listen reg3 handler=3; if ok talk reg1 (8 bytes) then 3 listens reg1; $3e2|=$20000'),  # 0100c000.py
    0x0100d986: ('adb_nop', 'empty (link/unlk/rts), unreferenced'),  # 0100c000.py
    0x0100d98e: ('adb_kbd_present', 'returns mg+$3e2 bit 0 (ADB keyboard found); unreferenced'),  # 0100c000.py
    0x0100d9aa: ('adb_dev_handler_stub', 'empty ADB register-0 data handler used for all device slots except 2 in table 0101b114'),  # 0100c000.py
    0x0100d9b4: ('scsi_init', '(mg): alloc softc(0x21e) -> mg+$186; DMA ctrl $22/$20; cfg1 $57; CCF 5 (Turbo); seltimeout $99; sync 5/0; bus reset; cfg1 $17'),  # 0100c000.py
    0x0100db8e: ('scsi_run_cmd', "(mg,?,sd): mg+$302=scsi_intr; scstart; poll INT_SCSI (bit12) up to 1000x10ms calling scsi_intr; 'Didn't complete'; ret 1 ok"),  # 0100c000.py
    0x0100dc44: ('scsi_start', '(softc,sd) scstart: CDB len by group, control byte must be 0; FIFO <- IDENTIFY(lun)|$80 + CDB; ESP cmd $42 SELATN'),  # 0100c000.py
    0x0100dd4e: ('scsi_intr', '(softc) scintr: DMA flush ($3c/$38 x3) if state 4; read status/seqstep/intstatus; bus reset wait; dispatch on state tab 01012a3c'),  # 0100c000.py
    0x0100de50: ('scsi_intr_selected', "state 1: DC -> sd state 1 (no target); seqstep 2/4 and intstatus $18 -> state 2 (phase dispatch) else 'selection failed'"),  # 0100c000.py
    0x0100de86: ('scsi_intr_state6', 'state 6 (after PAD transfer): go to phase dispatch'),  # 0100c000.py
    0x0100de9a: ('scsi_intr_dma_done', "state 4: resid = ESP count regs; update $214/$218; dma_cleanup; softc+$2c & $4000 -> 'bus error'"),  # 0100c000.py
    0x0100dee2: ('scsi_intr_status', "state 3 (after ICCS $11): DC -> 'target aborted'; FC and fifo==2 -> status byte to sd+$1c, msg byte to $21c, msgin"),  # 0100c000.py
    0x0100df1e: ('scsi_intr_msgin', 'state 7 (after TI $10 in MSG IN): fifo must be 1 -> msg byte to softc+$21c, call sub_0100e11e'),  # 0100c000.py
    0x0100df5e: ('scsi_intr_complete', 'state 5: softc state 0, current sd cleared, sd+$18 = resid, sd+$1d = 2 (done)'),  # 0100c000.py
    0x0100df74: ('scsi_intr_bad_state', "states 0/2: print 'scintr program error'"),  # 0100c000.py
    0x0100df9e: ('scsi_phase_dispatch', '(softc): ESP cmd 1 (flush FIFO); phase = status&7 -> tab 01012a5c (DATA OUT/IN, STATUS, MSG IN; others error)'),  # 0100c000.py
    0x0100dfe4: ('scsi_phase_data_out', 'DATA OUT: dir must be write; count 0 -> PAD $98 state 6; else dma_setup/start, ESP count, cmd $90 (DMA TI), DMA ctrl $30'),  # 0100c000.py
    0x0100e05e: ('scsi_phase_datain', 'DATA IN phase: set up DEV2M DMA chain, ESP count, cmd $90 DMA-xfer, ESP_DMA_CTRL=$38 (or pad if count 0)'),  # 0100e000.py
    0x0100e0e6: ('scsi_phase_status', 'STATUS phase: sc state=3, ESP cmd $11 (Initiator Command Complete)'),  # 0100e000.py
    0x0100e0f4: ('scsi_phase_msgin', 'MESSAGE IN phase: sc state=7, ESP cmd $10 (Transfer Information, PIO)'),  # 0100e000.py
    0x0100e106: ('scsi_phase_msgout_err', "MESSAGE OUT phase is unexpected: abort with 'SCSI msgout phase'"),  # 0100e000.py
    0x0100e10c: ('scsi_phase_error', 'common tail of the phase handlers: scsi_abort(sc, msg)'),  # 0100e000.py
    0x0100e11e: ('scsi_msgin_done', 'after MSG IN byte: expect COMMAND COMPLETE (0) and FUNCCMPLT, state=5, ESP cmd $12 (Message Accepted)'),  # 0100e000.py
    0x0100e188: ('scsi_abort', "print 'sc: %s', stop SCSI DMA (ESP_DMA_CTRL=$20), mark sd disconnected, reset ESP via sub_0100d9b4(0,0)"),  # 0100e000.py
    0x0100e1ec: ('sd_open', 'devops[0]: alloc sd (mg+$17e), reset ESP, find n-th target by INQUIRY, START UNIT, READ CAPACITY -> bd blksize/nblocks'),  # 0100e000.py
    0x0100e2f0: ('sd_close', 'devops[1]: no-op'),  # 0100e000.py
    0x0100e2f8: ('sd_find_target', 'scan targets 0..6 with INQUIRY; return the unit-th responding target or -1 (stops on bus hung)'),  # 0100e000.py
    0x0100e356: ('sd_inquiry', 'INQUIRY $12 len $42 into sd data buf; ok if device type 0,4,5,7,8; 3 tries'),  # 0100e000.py
    0x0100e40a: ('sd_read_capacity', 'READ CAPACITY $25 (8 bytes) into sd data buf; returns buf ptr (last LBA, blk len) or 0; 3 tries'),  # 0100e000.py
    0x0100e49a: ('sd_request_sense', 'REQUEST SENSE $03 len 14 into sd data buf; 3 tries; 1 s delay on BUSY'),  # 0100e000.py
    0x0100e548: ('sd_start_unit_wait_ready', "START STOP UNIT $1b (Immed, Start) then TEST UNIT READY loop; prints 'waiting for drive to come ready' + dots"),  # 0100e000.py
    0x0100e646: ('sd_read', 'devops[2](mg,bd,blkno,addr,len): READ(6) $08 via DMA, len must be multiple of blksize, 3 tries; returns bytes or -1'),  # 0100e000.py
    0x0100e726: ('sd_write_stub', 'devops[3]: no-op (no write support in ROM)'),  # 0100e000.py
    0x0100e72e: ('sd_label_blkno', 'devops[4](mg,bd,size,i): block number of disk-label copy i = ceil(size/blksize)*i'),  # 0100e000.py
    0x0100e750: ('sd_command', 'issue sd CDB via sub_0100db8e; on CHECK CONDITION do REQUEST SENSE, on BUSY wait 1 s; returns 1 ok / 0 fail'),  # 0100e000.py
    0x0100e7ee: ('sd_print_error', "print '%s: ' + selection timeout / sense key / busy / disconnected / driver refused message"),  # 0100e000.py
    0x0100e8cc: ('dma_init', 'CSR=DMA_RESET, clear flags, sc+$38=16-byte scratch, sc+$e4=8K-aligned bounce buffer at top-of-RAM-64K'),  # 0100e000.py
    0x0100e94a: ('dma_setup_chain', '(sc,chain,addr,len,dir): build 2-entry chain in bounce buffer (+scratch tail), copy data for M2DEV'),  # 0100e000.py
    0x0100ea5a: ('dma_cleanup', '(sc,resid): dma_stop, copy scratch tail back, copy bounce buffer to caller for DEV2M'),  # 0100e000.py
    0x0100eacc: ('dma_start', '(sc,chain,dir): CSR=dir|RESET|BUFRESET, load next/limit(+start/stop), CSR=dir|SETENABLE(|SETSUPDATE)'),  # 0100e000.py
    0x0100eb90: ('dma_stop', "save CSR status bits (sc+$24), CSR=DMA_RESET, save 'next' reg (sc+$28), clear flags"),  # 0100e000.py
    0x0100ebc4: ('boot_fs_open', 'fsops[0]: alloc 8K-aligned label buffer (mg+$182) + 8K sector cache, call devops[0] open'),  # 0100e000.py
    0x0100ec4e: ('boot_fs_load', 'fsops[2]: skip name to flags, read+check label, pick bootfile, load boot block 0/1 and run it'),  # 0100e000.py
    0x0100ed2e: ('boot_read_label', 'try label copies 0..3: read $1c48 bytes at devops[4] blkno, validate with boot_check_label'),  # 0100e000.py
    0x0100edc4: ('boot_check_label', 'NeXT/dlV2 ($1c48 B) or dlV3 ($230 B): check version, label_blkno and 16-bit checksum'),  # 0100e000.py
    0x0100ee54: ('boot_exec_blk0', "(mg,bd,byteoff): read 1 KB, parse a.out/Mach-O header, load image, build 'dev(c,u,p)file' and jump"),  # 0100e000.py
    0x0100ef50: ('boot_fs_seek', 'set current byte offset (labelbuf+$1c50)'),  # 0100e000.py
    0x0100ef66: ('boot_fs_read', "(mg,bd,dst,len): read through 8 KB block cache via devops[2]; returns len or -1 ('short read' by caller)"),  # 0100e000.py
    0x0100f044: ('boot_fs_close', 'fsops[1]: call devops[1] close'),  # 0100e000.py
    0x0100f060: ('od_ctrl_init', '(regs,ctrl,quiet,nowait): probe OSP at $02112000, alloc od softc mg+$18a, write init/format/mark/flags regs, DMA $02000050'),  # 0100e000.py
    0x0100f166: ('od_volume_init', "alloc od volume struct mg+$18e, drive type 'Canon OMD-1', read label via sub_010100aa, bd blksize=1024"),  # 0100e000.py
    0x0100f22e: ('od_label_blkno', 'devops[4](.,.,.,i): label copy sector from table $0101b358 (0, $3c460, -1, -1)'),  # 0100e000.py
    0x0100f244: ('od_open', 'devops[0]: refuse on machine type 1/3, ctrl must be 0, unit <=1, od_ctrl_init + od_volume_init'),  # 0100e000.py
    0x0100f2c0: ('od_close', 'devops[1]: no-op'),  # 0100e000.py
    0x0100f2c8: ('od_read', 'devops[2](mg,bd,blkno,addr,len): sub_01010004(cmd 2 read, ..., flags $80000); returns len'),  # 0100e000.py
    0x0100f2fe: ('od_write_stub', 'devops[3]: no-op'),  # 0100e000.py
    0x0100f306: ('od_strategy', '(iob,flag): len must be multiple of sector size else error $16; od_start_io'),  # 0100e000.py
    0x0100f35a: ('od_start_io', 'copy iob sector/addr/len into od softc ($4254/$210/$4260/$4264), clear retry counters, dispatch cmd 1'),  # 0100e000.py
    0x0100f3e0: ('od_cmd_dispatch', '(od,vol,cmd,iob): od+$4281=cmd, clear bits 30/29, jump via table $01012a7c[cmd-1]'),  # 0100e000.py
    0x0100f43a: ('od_cmd_start', 'cmd 1: clip chunk to track/alt-group, compute physical track+sector, select head or spiral-on/RID/eject'),  # 0100e000.py
    0x0100f66c: ('od_cmd_seek_low', 'cmd 2: send DRV_SEK (track & $fff) with head-select pending, next cmd from table $0101b3b2'),  # 0100e000.py
    0x0100f696: ('od_cmd_resume', 'cmd 8: clear bit 23 and re-dispatch saved cmd od+$4285'),  # 0100e000.py
    0x0100f6ac: ('od_cmd_fail_ret', 'cmd 12: return -1'),  # 0100e000.py
    0x0100f6b2: ('od_cmd_check_motor', 'cmd 13: DRV_RDS; if DS_STOPPED send DRV_STM start motor (cmd $e) else finish (cmd 14)'),  # 0100e000.py
    0x0100f6fa: ('od_cmd_finish', 'cmd 14: clear bits 24/17, mark iob done (|=2)'),  # 0100e000.py
    0x0100f716: ('od_cmd_after_eject', 'cmd 7: clear vol bits 15/14, od bit 23; bit 12 -> error finish else next chunk'),  # 0100e000.py
    0x0100f734: ('od_cmd_next_chunk', 'cmd 5: sectors -= done; advance addr/sector and re-run cmd 1, or mark iob done'),  # 0100e000.py
    0x0100f778: ('od_cmd_error_finish', "cmd 6: print 'failed', iob+$1c=error code, iob |= 6"),  # 0100e000.py
    0x0100f796: ('od_cmd_xfer', 'cmd 3/4/9/10/11: write track hi/lo, sector|$10, count to OSP regs, od_issue, od_complete'),  # 0100e000.py
    0x0100f7dc: ('od_complete', 'read/clear OSP int status + err stat, map to error code, read drive status, retry/restore/re-spin/eject logic'),  # 0100e000.py
    0x0100fadc: ('od_issue', 'start MO DMA (chain, dir by op), send pending drive cmd or CSR2, write formatter cmd to CSR1, poll DMA complete'),  # 0100e000.py
    0x0100fc00: ('od_drive_cmd', '(od,vol,cmd16,flags): CSR2=drive sel|$80, wait CMD_COMPL, write CSR_H/CSR_L, wait; err $3a/$3b on timeout'),  # 0100e000.py
    0x0100fcec: ('od_print_error', "(od,action): 'od%d%c: %s %s (%s) trk:0:sec' using op name and error table $0101b1d8"),  # 0100e000.py
    0x0100fdc6: ('od_read_drive_status', 'DRV_RDS/RES/RHS status words -> od+$4266/$4268/$426a, map error bits via tables, then DRV_RID'),  # 0100e000.py
    0x0100ff6a: ('od_drive_query', '(od,vol,regs,cmd,flags): send drive cmd, 40 us, CSR1=$20 read-status, return 16-bit reply from CSR_H/L'),  # 0100e000.py
    0x01010002: ('stub_rts', 'bare rts; only reached through pointer tables at 0100cbec/0100d004/0100d88a'),  # 01010000.py
    0x01010004: ('od_cmd', 'OD driver: queue op (F0 probe, F1 eject, 2 read) in od cmd block, poll done; 0 ok / 5 err+status'),  # 01010000.py
    0x010100aa: ('od_read_label', 'OD: probe drive (op F0), then read label at each candidate block, verify; 0 ok, 1/2/3 drive err, 4 no label'),  # 01010000.py
    0x01010218: ('disk_label_check', 'verify NeXT disk label: magic NeXT/dlV2 (sum @1c46) or dlV3 (sum @22e), blkno match; 0 ok / -1'),  # 01010000.py
    0x0101027e: ('od_eject', 'on machine type 0/2 open OD (ctrl 1) and issue op F1 (eject); returns 0 or -1'),  # 01010000.py
    0x0101030e: ('od_reset', 'machine type 0/2 only: write 1 (MOINT_RESET) to MO int-status $02112004, wait 100, write 0'),  # 01010000.py
    0x0101034c: ('od_query_status', 'machine type 0/2: open OD, run sub_0100ff6a(od,$2000,9), return bit14 of result (uncertain)'),  # 01010000.py
    0x010103d0: ('fd_probe_media', 'recalibrate x2, read media id, autodetect density 3..1 x secsize 512/1024 by test reads; 0/1/3/4'),  # 01010000.py
    0x01010562: ('fd_open', 'device-switch open: alloc fcp ($704) at mg+$3a4, fc_init, fd_probe_media, print fd errors, fill size'),  # 01010000.py
    0x01010680: ('fd_close', 'device-switch entry: empty'),  # 01010000.py
    0x01010688: ('fd_read', 'device-switch read(mg,x,sector,buf,len): fd_setup_io(fvp,sector,len/secsize,buf,read); bytes done or -1'),  # 01010000.py
    0x010106d6: ('fd_write_nop', 'device-switch entry: empty (ROM never writes floppies)'),  # 01010000.py
    0x010106de: ('fd_round_to_sectors', 'device-switch entry: ceil(len/secsize)*arg'),  # 01010000.py
    0x01010700: ('fd_eject', 'monitor eject: fd_open(ctrl1,unit,noprobe,quiet) then fd_simple_cmd(fvp,2=EJECT)'),  # 01010000.py
    0x0101075a: ('fd_raw_cmd', 'copy cmd block into fvp+8, set raw flag, run fd_run_io, copy back; -1 on error'),  # 01010000.py
    0x010107bc: ('fd_run_io', 'fd state machine: set retries (2 retry,1 recal), state=1, loop fc_start until state 0; returns bytes left'),  # 01010000.py
    0x0101080e: ('fd_intr', 'completion: account bytes moved, then switch on cmd status (table 01012ab4)'),  # 01010000.py
    0x0101089e: ('fd_intr_ok', 'cmd status 0: state 2->1, 3->2; continue if bytes remain else state 0'),  # 01010000.py
    0x010108e2: ('fd_intr_error', 'cmd status err: RETRY, then RECALIBRATE, then FATAL (prints fd%d: Sector %d ...)'),  # 01010000.py
    0x01010970: ('fd_intr_fatal', 'unknown cmd status: print FATAL and stop'),  # 01010000.py
    0x01010988: ('fd_print_error', 'printf fd%d: Sector %d(d) cmd = Read/W; status = %d: %s'),  # 01010000.py
    0x010109c8: ('fd_start_transfer', 'limit chunk to end of track, save sector/len/buf, build R/W command'),  # 01010000.py
    0x01010a62: ('fd_build_rw_cmd', '82077 READ(06)/WRITE(05) DATA cmd bytes MT=0 MFM,C,H,R,N,EOT,GPL,DTL=ff; 9 bytes, 7 results'),  # 01010000.py
    0x01010b4a: ('fd_setup_io', 'fvp: sector, buffer, nsectors*secsize, read flag (bit0 of fvp+$92) -> fd_run_io'),  # 01010000.py
    0x01010b92: ('fd_probe_read', 'read nsectors at sector into buffer via raw cmd (used by fd_probe_media)'),  # 01010000.py
    0x01010be8: ('fd_sense_media', 'raw cmd type 5 (no 82077 cmd): returns media-id/motor byte in *arg'),  # 01010000.py
    0x01010c26: ('fd_recalibrate', 'build RECALIBRATE(07) cmd and run it as raw cmd'),  # 01010000.py
    0x01010c54: ('fd_simple_cmd', 'raw cmd of type arg (2=eject, 4=motor off) with 10ms timeout'),  # 01010000.py
    0x01010c92: ('fd_build_recal_cmd', 'cmd bytes 07,drive; timeout 1000, 2 cmd bytes, 2 result bytes'),  # 01010000.py
    0x01010ce0: ('fd_lba_to_chs', 'C=lba/spt/heads, H=(lba/spt)%heads, R=lba%spt+1 into cmd bytes 2..4'),  # 01010000.py
    0x01010d36: ('fd_vol_init', 'zero fvp ($c2), density=2, unit, flags'),  # 01010000.py
    0x01010d70: ('fd_set_density', 'copy 14-byte entry for density key from dat_0101b448 to fvp+$a8 (capacity,GPL,MFM)'),  # 01010000.py
    0x01010dba: ('fd_set_geometry', 'secsize -> spt = cap/(heads*cyls)/secsize, total = heads*spt*cyls; mark geometry valid'),  # 01010000.py
    0x01010e14: ('fc_init', 'fcp: 82077 base $02114100, ext ctrl $02114108=$40, fc_reset, DMA chan CSR $02000010, ESP DMA ctrl $02114020'),  # 01010000.py
    0x01010e96: ('fc_start', 'run cmd block: select drive in DOR, dispatch cmd type 1..5 (table 01012af8), media status, hang check'),  # 01010000.py
    0x01010f3a: ('fc_start_type1', 'cmd type 1: fc_do_command'),  # 01010000.py
    0x01010f48: ('fc_start_type2', 'cmd type 2: fc_eject, fvp state=2'),  # 01010000.py
    0x01010f58: ('fc_start_type3', 'cmd type 3: fc_motor_on'),  # 01010000.py
    0x01010f62: ('fc_start_type4', 'cmd type 4: fc_motor_off'),  # 01010000.py
    0x01010f76: ('fc_start_type5', 'cmd type 5: no controller command, status 0'),  # 01010000.py
    0x0101100e: ('fc_intr', 'floppy IRQ service: flush ESP DMA (x1/x8), wait RQM; DIO=0 -> send SENSE INT (08) else read ST0'),  # 01010000.py
    0x010110d8: ('fc_reset', 'print fc: Controller Reset, DOR=0, 250us, DOR=4, DSR=0, CCR=0, ext ctrl=$40, fc_configure, fc_specify'),  # 01010000.py
    0x01011182: ('fc_send_byte', 'wait RQM&DIO=0 then write FIFO $02114105'),  # 01010000.py
    0x010111b0: ('fc_get_byte', 'wait RQM&DIO=1 then read FIFO into *arg'),  # 01010000.py
    0x010111dc: ('fc_wait_rqm', 'poll MSR up to 80000x for RQM; 0 ok, 1 = poll count hit $3e80, $a = DIO mismatch (phase)'),  # 01010000.py
    0x01011230: ('fc_ctrl_set', 'ext control $02114108 |= arg (shadow fcp+$10)'),  # 01010000.py
    0x0101124e: ('fc_ctrl_clr', 'ext control $02114108 &= ~arg (shadow fcp+$10)'),  # 01010000.py
    0x0101126e: ('fc_read_media_status', 'cmd+$4e: bit5 = DOR motor bit for drive, bits7:6 = ext status media id'),  # 01010000.py
    0x010112ba: ('fc_configure', '82077 CONFIGURE 13 00 58 00 (EIS, FIFO on, no poll, thr 8) via fc_send_cmd'),  # 01010000.py
    0x0101130e: ('fc_specify', 'SPECIFY 03 SRT/HUT HLT from drive table; DSR/CCR rate 2/0/3 for density 1/2/3; else Bogus density'),  # 01010000.py
    0x0101148c: ('fc_do_command', 'type 1: OR drive into cmd byte1, specify if density changed, motor on for r/w ops, send'),  # 01010000.py
    0x01011536: ('fc_cmd_motor_on', 'opcodes needing spindle: fc_motor_on, ext status bit2 set -> status 5 (no drive)'),  # 01010000.py
    0x01011554: ('fc_cmd_send', 'fc_send_cmd and store status in cmd+$3e'),  # 01010000.py
    0x0101156c: ('fc_eject', 'motor on, SEEK cyl 79, ext ctrl |= $80 then &= ~$80, wait 2s, motor off'),  # 01010000.py
    0x01011616: ('fc_build_seek_cmd', 'SEEK 0F, head<<2, cyl; timeout 400, 3 cmd bytes, 2 results'),  # 01010000.py
    0x01011670: ('fc_motor_on', 'DOR |= $10<<drive if not already, wait 500ms'),  # 01010000.py
    0x010116ac: ('fc_motor_off', 'DOR &= ~($10<<drive)'),  # 01010000.py
    0x010116d2: ('fc_send_cmd', 'set up DMA (ESP ctrl $08=dev->mem,$10 dma), send cmd bytes, wait IRQ/immediate, results, check'),  # 01010000.py
    0x01011864: ('fc_cmd_wait_intr', 'opcodes with execution phase: fd_wait_intr(timeout ms*1000)'),  # 01010000.py
    0x0101187e: ('fc_cmd_result_phase', 'after exec: pulse ESP flush (x1/x8), clear DMA mode; then result bytes and DMA accounting'),  # 01010000.py
    0x010119e8: ('fc_check_rw_result', 'ok if IC=0, or ST1==$80, or IC=$40 + all bytes DMAed + ST1.OR; else 8; no results -> $12'),  # 01010000.py
    0x01011a24: ('fc_check_seek_result', 'ST0 SE set and PCN == requested cyl else status 9'),  # 01010000.py
    0x01011a44: ('fc_check_recal_result', 'ST0 SE set, PCN 0 and status A TRK0_N low else status 9'),  # 01010000.py
    0x01011a60: ('fc_send_cmd_exit', 'dma_cleanup(fcp+$12) if DMA was started; return status (1 if timeout)'),  # 01010000.py
    0x01011a82: ('fc_dma_reset', 'dummy 16-byte dev->mem DMA setup/start, 10us, dma_stop: clears the SCSI/floppy DMA channel'),  # 01010000.py
    0x01011ae8: ('dma_bytes_moved', 'walk up to 10 DMA chain entries against TDMA saved next ptr ($4000 off CSR); bytes done'),  # 01010000.py
    0x01011b6c: ('fd_wait_intr', 'poll int status $02007000 for INT_PHONE ($80) up to us/1000 ms; run fc_intr; 1 on timeout'),  # 01010000.py
    0x01011bf0: ('jt_machine_type_01000d4c', '12 x dc.l: machine type 0..11 switch in loc_01000d4c'),  # 01010000.py
    0x01011c20: ('jt_01001d32', '8 x dc.l: switch in loc_01001d32 (bfextu $92(a6){0:4})'),  # 01010000.py
    0x01011c40: ('jt_01001eec', '53 x dc.l: switch at 01001eec'),  # 01010000.py
    0x01011d14: ('jt_boot_01006554', '5 x dc.l: switch at 01006554'),  # 01010000.py
    0x01011d28: ('jt_char_010078bc', '84 x dc.l: character switch (c-0x25 .. 0x53) at 010078bc'),  # 01010000.py
    0x01011e78: ('jt_0100a456', '8 x dc.l: switch at 0100a456'),  # 01010000.py
    0x01011e98: ('jt_0100a65c', '7 x dc.l: switch at 0100a65c (d3-7 .. 6)'),  # 01010000.py
    0x01011eb4: ('jt_0100a93e', '32 x dc.l: unrolled-loop entry table for 0100a93e (jmp (a0,d5))'),  # 01010000.py
    0x01011f34: ('jt_0100b3d2', '42 x dc.l: switch on d2>>26 at 0100b3d2'),  # 01010000.py
    0x01011fdc: ('jt_0100b972', '9 x dc.l: machine type-3 switch at 0100b972'),  # 01010000.py
    0x01012000: ('tbl_sqrt16', '256 x dc.b: 16*sqrt(i) ramp (0..255), read by 0100bdb6 and 0100bf22'),  # 01010000.py
    0x01012100: ('jt_0100bf72', '9 x dc.l: machine type-3 switch at 0100bf72'),  # 01010000.py
    0x01012124: ('tmc_alt_timing_tab', '6 pointers, machine type 4..9: mono types -> tmc_alt_timing_mono, colour -> tmc_alt_timing_color'),  # 0100c000.py
    0x0101213c: ('jt_0100c93c', '72 x dc.l: switch at 0100c93c'),  # 01010000.py
    0x0101225c: ('jt_0100ca66', '72 x dc.l: switch at 0100ca66'),  # 01010000.py
    0x0101237c: ('jt_0100cd4c', '72 x dc.l: switch at 0100cd4c'),  # 01010000.py
    0x0101249c: ('jt_0100ce76', '72 x dc.l: switch at 0100ce76'),  # 01010000.py
    0x010125bc: ('jt_0100d178', '72 x dc.l: switch at 0100d178'),  # 01010000.py
    0x010126dc: ('jt_0100d2a2', '72 x dc.l: switch at 0100d2a2'),  # 01010000.py
    0x010127fc: ('jt_0100d5d2', '72 x dc.l: switch at 0100d5d2'),  # 01010000.py
    0x0101291c: ('jt_0100d6fc', '72 x dc.l: switch at 0100d6fc'),  # 01010000.py
    0x01012a3c: ('scsi_intr_state_tab', '8 pointers indexed by softc state 0..7'),  # 0100c000.py
    0x01012a5c: ('scsi_phase_tab', '8 pointers indexed by SCSI bus phase (ESP status & 7)'),  # 0100c000.py
    0x01012a7c: ('jt_0100f42e', '14 x dc.l: switch at 0100f42e'),  # 01010000.py
    0x01012ab4: ('jt_fd_intr_status', '17 x dc.l: fd_intr switch on cmd status 0..16'),  # 01010000.py
    0x01012af8: ('jt_fc_start_type', '5 x dc.l: fc_start switch on cmd type 1..5'),  # 01010000.py
    0x01012b0c: ('jt_fc_do_command_op', '21 x dc.l: fc_do_command switch on 82077 opcode 2..22'),  # 01010000.py
    0x01012b60: ('jt_fc_send_cmd_op', '29 x dc.l: fc_send_cmd wait-phase switch on opcode 3..31'),  # 01010000.py
    0x01012bd4: ('jt_fc_result_op', '11 x dc.l: fc_send_cmd result-check switch on opcode 5..15'),  # 01010000.py
    0x01012c00: ('str_regnames_0_7', "'0'..'7' NUL strings shared by the d- and a-register tables (tbl_regs_d/tbl_regs_a)"),  # 01012c00.py
    0x01012c10: ('str_reg_pc', "'pc' name string of tbl_regs_ctl"),  # 01012c00.py
    0x01012c16: ('bits_sr', '%b-style bit descriptor for SR: radix byte, then (bit+1|0x80=when-clear|0xC0 field,width) name'),  # 01012c00.py
    0x01012c36: ('str_reg_usp', "'usp'"),  # 01012c00.py
    0x01012c3a: ('str_reg_isp', "'isp'"),  # 01012c00.py
    0x01012c3e: ('str_reg_msp', "'msp'"),  # 01012c00.py
    0x01012c42: ('str_reg_vbr', "'vbr'"),  # 01012c00.py
    0x01012c46: ('str_reg_sfc', "'sfc'"),  # 01012c00.py
    0x01012c4a: ('str_reg_dfc', "'dfc'"),  # 01012c00.py
    0x01012c4e: ('str_reg_cacr', "'cacr'"),  # 01012c00.py
    0x01012c64: ('bits_intr_old', 'bit descriptor of interrupt status/mask, NeXT Computer layout (optical, phone, m2r/r2m DMA)'),  # 01012c00.py
    0x01012ede: ('bits_scr1_new', 'SCR1 descriptor: [31:28]sid [15:12]machine [11:8]rev [7:6]vmss [5:4]mmss [2:0]cspd'),  # 01012c00.py
    0x010145c8: ('tbl_regs_d', "monitor 'd' command: d0..d7, offset 0..0x1c in the saved exception frame; zero-terminated"),  # 01012c00.py
    0x0101467c: ('tbl_regs_a', "monitor 'a' command: a0..a7, frame offset 0x20..0x3c"),  # 01012c00.py
    0x01014730: ('tbl_regs_ctl', "monitor 'r' command: pc +86 sr +82 usp +40 isp +44 msp +48 vbr +54 sfc +4c dfc +50 cacr +5c"),  # 01012c00.py
    0x010147f8: ('tbl_sysreg_old', "monitor 's' command when mg+$194==0x139 (types 0-3): intrstat/intrmask/scr1/scr2 with old bit names"),  # 01012c00.py
    0x0101485c: ('tbl_sysreg_new', "monitor 's' command, Turbo (types 4-B): $02007000 $02007800 $0200C000 $0200D000, 040 bit names"),  # 01012c00.py
    0x010148c0: ('tbl_params', "13 NVRAM parameters edited by the monitor 'p' command; see notes for byte/bit map"),  # 01012c00.py
    0x010149c4: ('tbl_fcode_names', "8 names for 'S [fcode]': 0,UD,UP,3,4,SD,SP,cpu -> 'Function code %d (%s)'"),  # 01012c00.py
    0x010149e4: ('tbl_simm_names_nonturbo', '16 strings indexed by 4-bit SIMM code (size[1:0], page[2], parity[3]), non-Turbo'),  # 01012c00.py
    0x01014a24: ('tbl_simm_names_turbo', '16 strings indexed by 4-bit SIMM code, Turbo (32/8/2 MB pairs, parity[3])'),  # 01012c00.py
    0x01014a64: ('tbl_simm_size_nonturbo', '16 longs: bank size by SIMM code (0,16M,4M,1M repeated for page/parity bits)'),  # 01012c00.py
    0x01014aa4: ('tbl_simm_size_turbo', '16 longs: bank size by SIMM code, Turbo (0,32M,8M,2M repeated)'),  # 01012c00.py
    0x01014ae4: ('tbl_cpu_mhz_old', '8 bytes: SCR1 cspd[2:0] -> MHz for mg+$194==0x139 boards (16,20,25,33,40,50,66,80)'),  # 01012c00.py
    0x01014ae8: ('tbl_cpu_mhz', '8 bytes: SCR1 cspd -> MHz (40,50,66,80,16,20,25,33); 7=33 MHz Turbo; overridden to 40 if NCC'),  # 01012c00.py
    0x01014af0: ('tbl_mem_ns_old', '4 bytes: SCR1 mmss[5:4] -> DRAM ns, old boards (100,100,80,60)'),  # 01012c00.py
    0x01014af4: ('tbl_mem_ns', "4 bytes: SCR1 mmss[5:4] -> DRAM ns (60,70,80,100), printed by '%d MHz, memory %d nS'"),  # 01012c00.py
    0x01014af8: ('tbl_memtiming', '96x5 bytes copied to $02006010..14 (non-Turbo memory timing); idx=type*32+cspd*4+mmss'),  # 01012c00.py
    0x01014cd8: ('str_help', "monitor '?' help text (1096 bytes), printed by sub_01002c3c"),  # 01012c00.py
    0x01015030: ('tbl_vram_ic_letters', "4 x 'XYZ\\0': VRAM IC designators per byte lane for 'VRAM failure ... IC U%d'"),  # 01012c00.py
    0x01015040: ('img_icon_cube', "'S' RLE image 88x88, NeXTcube icon drawn at (640,353) when mg+$3b6==0"),  # 01012c00.py
    0x01015264: ('img_icon_station', "'S' RLE image 88x88, NeXTstation icon drawn at (640,353) when mg+$3b6==1"),  # 01012c00.py
    0x01015580: ('img_bigfont_sheet', "'S' RLE image 256x50: glyph sheet of the proportional boot font (see tbl_bigfont_metrics)"),  # 01012c00.py
    0x01015f74: ('img_next_logo', "'S' RLE image 440x176 drawn at (340,308) during POST/boot (large NeXT logo)"),  # 01012c00.py
    0x01016b3c: ('img_slotdrive', "'S' RLE 80x84: optical/floppy slot-drive icon, base frame of the disk animations"),  # 01012c00.py
    0x01017048: ('img_slotdrive_f1', "'S' RLE 72x41: disk-activity frame 1 (drawn at 640,368)"),  # 01012c00.py
    0x0101731c: ('img_slotdrive_f2', "'U' raw 2bpp 72x41: disk-activity frame 2"),  # 01012c00.py
    0x0101760a: ('img_arrow_1', "'U' raw 2bpp 16x17: 'insert disk' arrow frame 1 (672,384)"),  # 01012c00.py
    0x0101765a: ('img_arrow_2', "'U' raw 2bpp 16x17: arrow frame 2 (672,376)"),  # 01012c00.py
    0x010176aa: ('img_arrow_3', "'U' raw 2bpp 16x17: arrow frame 3 (672,368)"),  # 01012c00.py
    0x010176fa: ('img_flipdisk', "'U' raw 2bpp 32x20: 'please flip disk' frame (664,375)"),  # 01012c00.py
    0x010177a6: ('img_baddisk', "'S' RLE 80x41: 'bad disk' overlay frame"),  # 01012c00.py
    0x010179de: ('img_network', "'S' RLE 88x84: network icon, base frame"),  # 01012c00.py
    0x01017e7e: ('img_network_f1', "'S' RLE 88x63: network animation frame 1"),  # 01012c00.py
    0x0101826e: ('img_network_f2', "'S' RLE 88x63: network animation frame 2"),  # 01012c00.py
    0x01018666: ('img_scsidisk', "'S' RLE 80x95: SCSI hard disk icon (drawn at 640,347)"),  # 01012c00.py
    0x01018cb6: ('img_scsidisk_f1', "'U' raw 2bpp 72x65: SCSI disk activity frame 1"),  # 01012c00.py
    0x01019154: ('img_scsidisk_f2', "'U' raw 2bpp 72x65: SCSI disk activity frame 2"),  # 01012c00.py
    0x010195f4: ('tbl_scc_init', '20 bytes: SCC (reg,value) pairs written by post_scc_test: WR4=44 WR11=50 WR14=10 WR12=0A ...'),  # 01012c00.py
    0x01019608: ('enet_bcast_addr12', '12 x 0xFF; first 6 copied as the Ethernet broadcast address in the Ethernet POST'),  # 01012c00.py
    0x01019614: ('tbl_sine_1696', '1696 signed 16-bit samples of a decaying sine, sound-out test waveform (4x replicated)'),  # 01012c00.py
    0x0101a354: ('tbl_bootanim', '43 x 10 bytes {x,y,ptr,next,ticks}: boot-screen message/animation script'),  # 01012c00.py
    0x0101a4d0: ('tbl_bigfont_metrics', '6-byte glyph records indexed by ASCII (valid 0x20..0x7e at 0101a590): x,top,w,h,yoff,0'),  # 01012c00.py
    0x0101a502: ('tbl_bootdevs', '5 x 20 bytes {name,ops,ops2,desc,anim idx[4]}: en, tp, sd, od, fd; zero-terminated'),  # 01012c00.py
    0x0101a57c: ('enet_bcast_addr', '6 x 0xFF Ethernet broadcast address'),  # 01012c00.py
    0x0101a582: ('ops_en', "3 fn ptrs for 'en'/'tp' boot: 010069cc, 01006a2e, 01006a44 (+2 zero)"),  # 01012c00.py
    0x0101a890: ('str_hexdigits', "'0123456789abcdef' digit lookup for number parsing"),  # 01012c00.py
    0x0101a8a2: ('tbl_month_days', '13 words: cumulative days before month (0,0,31,59,...,334) for RTC date conversion'),  # 01012c00.py
    0x0101a8bc: ('scc_parity_table', '128-byte even-parity table (data, mis-decoded as code by the descent)'),  # 01008000.py
    0x0101a93c: ('scc_clock_table', '2 longs: 3686400 (PCLK) and 4000000 (RTxC) Hz'),  # 01008000.py
    0x0101a944: ('scc_ops_table', '4 ptrs: stub, stub, scc_getc, scc_putc'),  # 01008000.py
    0x0101a95c: ('enet_ops_table', 'netif ops: init, close, read, write, nop, 1'),  # 01008000.py
    0x0101a974: ('enet_addr_unset', "3 bytes FF FF FF compared with ROM MAC bytes 3..5 ('no address programmed')"),  # 01012c00.py
    0x0101a978: ('tbl_keymap', '2 x 81 keycodes x {unshift,shift} words (hi byte 1 = special key); second map at +0x144'),  # 01012c00.py
    0x0101ac00: ('font_8x12', '96 glyphs x 12 rows, 8 px wide, ASCII 0x20..0x7f: console text font'),  # 01012c00.py
    0x0101b080: ('tbl_console_backends', '3 x 7 fn ptrs {probe,init,..,set_brightness,..}; probe tried in order, winner in mg+$34d'),  # 01012c00.py
    0x0101b0d4: ('brightness_lfsr_tab', '64-byte table: 6-bit LFSR code for brightness level n (next = (v<<1 | !(b5^b4)) & $3f)'),  # 0100c000.py
    0x0101b114: ('adb_dev_handler_tab', '8 pointers indexed by device-table +0: [2] = adb_kbd_handler, others adb_dev_handler_stub'),  # 0100c000.py
    0x0101b134: ('adb_to_next_keycode_tab', '128-byte ADB keycode -> NeXT keycode table; entries >= $80 are F/nav keys mapped to Cmd+code'),  # 0100c000.py
    0x0101b1b4: ('ops_sd', '5 fn ptrs 0100e1ec,0100e2f0,0100e646,0100e726,0100e72e + flag 1: SCSI disk ops'),  # 01012c00.py
    0x0101b1cc: ('ops_disk_common', '3 fn ptrs 0100ebc4,0100f044,0100ec4e shared by sd/od/fd (label read/boot)'),  # 01012c00.py
    0x0101b1d8: ('tbl_od_status', '60 x 6 bytes {flags(top 3 bits = recovery action),0,msg}: optical drive status codes'),  # 01012c00.py
    0x0101b340: ('tbl_od_drives', "48-byte optical drive record: 'Canon OMD-1', blocks 0x3c460, block size 0x400, 0x40000 total"),  # 01012c00.py
    0x0101b358: ('od_params', 'longs returned by sub_0100f22e(param): 0,0x3c460,-1,-1,0x400,0x40000'),  # 01012c00.py
    0x0101b370: ('tbl_od_words', '3 words 0000 1035 0010 (optical drive parameters, unidentified)'),  # 01012c00.py
    0x0101b376: ('ops_od', '5 fn ptrs 0100f244,0100f2c0,0100f2c8,0100f2fe,0100f22e + 1: optical disk ops'),  # 01012c00.py
    0x0101b38e: ('od_retry_max', "long 2 compared with the retry counter before 'failed'"),  # 01012c00.py
    0x0101b392: ('tbl_od_actions', '4 strings: retry, restore, re-spin, failed'),  # 01012c00.py
    0x0101b3a2: ('od_cmd_template', '7 bytes 35 00 00 33 44 35 33 copied into the optical command block (+0xd byte 0x26)'),  # 01012c00.py
    0x0101b3b2: ('tbl_od_bytes', '10 bytes indexed by mg-struct byte $4278 -> $4282 (optical, unidentified)'),  # 01012c00.py
    0x0101b3bc: ('ops_fd', '5 fn ptrs 01010562,01010680,01010688,010106d6,010106de + 1: floppy ops'),  # 01012c00.py
    0x0101b3d4: ('tbl_fd_drives', "60-byte floppy drive record: 'Sony MPX-111N' + parameters"),  # 01012c00.py
    0x0101b410: ('tbl_fd_density', '14-byte records keyed by density code 3/2/1: {key, sides 2, 0, cyl 80, 0, format idx}'),  # 01012c00.py
    0x0101b448: ('tbl_fd_formats', '14-byte records keyed by format idx 1/2/3/0: {key, bytes 720K/1.44M/2.88M/720K, rate 8/10/20/30,..}'),  # 01012c00.py
}
