#!/usr/bin/env python3
"""Merge the per-range name fragments in names/*.py into known_names.py.

Each fragment defines KNOWN = {addr: (name, note)}.  Conflicts (same address,
different name) and duplicate names (same name, different address) are reported;
the first fragment in sorted file order wins.  Addresses must be even and inside
the ROM.  Run disasm_rom.py afterwards to apply the names.

    python rom-dissassembly/merge_names.py
"""
import glob, os, re, sys, importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
BASE, END = 0x01000000, 0x01020000
merged = {}
origin = {}
by_name = {}
problems = []
for path in sorted(glob.glob(os.path.join(HERE, "names", "*.py"))):
    spec = importlib.util.spec_from_file_location("frag", path)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as e:
        problems.append("%s: cannot load: %s" % (os.path.basename(path), e)); continue
    frag = getattr(mod, "KNOWN", {})
    for a, v in frag.items():
        if not isinstance(v, (tuple, list)) or len(v) != 2:
            problems.append("%s: %08x: value must be (name, note)" % (os.path.basename(path), a)); continue
        name, note = v
        if not (BASE <= a < END) or a & 1:
            problems.append("%s: %08x: bad address" % (os.path.basename(path), a)); continue
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            problems.append("%s: %08x: bad name %r" % (os.path.basename(path), a, name)); continue
        if a in merged and merged[a][0] != name:
            problems.append("conflict at %08x: %s (%s) vs %s (%s); keeping the first" % (a, merged[a][0], origin[a], name, os.path.basename(path))); continue
        if name in by_name and by_name[name] != a:
            name2 = "%s_%08x" % (name, a)
            problems.append("duplicate name %s at %08x (already %08x): renamed to %s" % (name, a, by_name[name], name2))
            name = name2
        merged[a] = (name, note.strip())
        origin[a] = os.path.basename(path)
        by_name[name] = a

out = ["# Generated by merge_names.py from names/*.py -- do not edit; edit the fragments.", "KNOWN = {"]
for a in sorted(merged):
    name, note = merged[a]
    out.append("    0x%08x: (%r, %r),  # %s" % (a, name, note, origin[a]))
out.append("}")
open(os.path.join(HERE, "known_names.py"), "w", newline="\n").write("\n".join(out) + "\n")
print("%d names merged into known_names.py" % len(merged))
for p in problems: print("  " + p)
